ITEM.name = "Molotov Cocktail"
ITEM.model = ("models/weapons/ethereal/w_molotov.mdl")
ITEM.description = "A Molotov Cocktail, for when the Party needs a bit more heat."
ITEM.class = "cw_kk_ins2_nade_molotov"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2500
ITEM.flag = "1"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.54