ITEM.name = "RGD-1 Smoke Grenade"
ITEM.model = ("models/silver/stalker/weapons/w_rgd1.mdl")
ITEM.description = "A RGD-1 Smoke Grenade"
ITEM.class = "cw_sil_nade_rgd1"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 2
ITEM.price = 1500
ITEM.flag = "1"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.538