ITEM.name = "Breaching Charge"
ITEM.model = ("models/weapons/w_c4.mdl")
ITEM.description = "An explosive charge meant for making a really big fucking hole."
ITEM.longdesc = "A block of C2, meant for breaching structures and taking down doors. It causes a volatile inwards blast upon detonation, harming those unfortunate to be on the receiving end."
ITEM.class = "cw_kk_ins2_nade_c4"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 2
ITEM.height = 1
ITEM.price = 55000
ITEM.flag = "A"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 2.0