ITEM.name = "RGN Grenade"
ITEM.model = ("models/silver/outbreak/weapons/w_rgn.mdl")
ITEM.description = "A RGN Impact Grenade"
ITEM.class = "cw_sil_nade_rgn"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8500
ITEM.flag = "3"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.6