ITEM.name = "Razor Bomb"
ITEM.model = ("models/silver/outbreak/weapons/w_vog25.mdl")
ITEM.description = "A Makeshift Grenade with the razor-sharp ends of a broken up Spike duct taped on for extra shrapnel damage. \n\nCauses bleeding wound of current level +2"
ITEM.class = "cw_sil_nade_vog25"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 1
ITEM.price = 0
ITEM.flag = "A"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.25