ITEM.name = "F1 Grenade"
ITEM.model = ("models/weapons/ethereal/w_f1.mdl")
ITEM.description = "A F1 Grenade"
ITEM.class = "cw_kk_ins2_nade_f1"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 1
ITEM.price = 5000
ITEM.flag = "3"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.6