ITEM.name = "IED"
ITEM.model = ("models/weapons/w_ied.mdl")
ITEM.description = "A improvised explosive device."
ITEM.class = "cw_kk_ins2_nade_ied"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 2
ITEM.price = 25000
ITEM.flag = "4"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 2.2