ITEM.name = "RGD5 Grenade"
ITEM.model = ("models/silver/stalker/weapons/w_rgd5.mdl")
ITEM.description = "A RGD5 Grenade"
ITEM.class = "cw_sil_nade_rgd5"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3500
ITEM.flag = "3"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.6