CustomizableWeaponry:addFireSound("CW_SIL_GAUSS_FIRE", "weapons/gauss_rifle/gauss_fire.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_SIL_GAUSS_FIRE_SUPPRESSED", "weapons/gauss_rifle/gause_fire.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addRegularSound("CW_SIL_GAUSS_DRAW", "weapons/gauss_rifle/gauss_draw.wav")
CustomizableWeaponry:addRegularSound("CW_SIL_GAUSS_HOLSTER", "weapons/gauss_rifle/gauss_holster.wav")

CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_BOLTBACK", "weapons/fnfal/handling/fnfal_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_BOLTRELEASE", "weapons/fnfal/handling/fnfal_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_EMPTY", "weapons/fnfal/handling/fnfal_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_FIRESELECT", "weapons/fnfal/handling/fnfal_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGIN", "weapons/fnfal/handling/fnfal_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGOUT", "weapons/fnfal/handling/fnfal_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGOUTRATTLE", "weapons/fnfal/handling/fnfal_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_MAGRELEASE", "weapons/fnfal/handling/fnfal_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_FNFAL_RATTLE", "weapons/fnfal/handling/fnfal_rattle.wav")