ITEM.name = "Steyr AUG A3"
ITEM.description= "A bull-pup assault rifle. Fires 5.56x45mm."
ITEM.longdesc = "The AUG is an Austrian assault rifle designed around the 60-70's and remains a viable solution to this day. \nIt's a bullpup configuration rifle, the magazine behind the handguard results in a shorter length. \nIt's not fully ambidextrious, but it can be changed for left-hand shooters if one changes the bolt with one that has the extractor and ejector on the other side.\n\nAmmo: 5.56x45mm \nMagazine Capacity: 30"
ITEM.model = "models/silver/stalker/weapons/w_auga3.mdl"
ITEM.class = "cw_sil_aug"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.price = 45000 
ITEM.height = 2
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 3.3
ITEM.flag = "3"
ITEM.iconCam = {
	pos = Vector(5.5, 27, 6),
	ang = Angle(0, 270, 0),
	fov = 70
}
ITEM.Range = 100
ITEM.Pen = 12
ITEM.Mag = 30
ITEM.barrel = "medium"
