ITEM.name = "ASh-12.7"
ITEM.description = "A battle rifle that fires 12.7x55mm STs-130 rounds."
ITEM.longdesc = "The ASh-12.7 battle rifle is a dedicated Urban Operations weapon, developed by TsKIB SOO, a subsidiary of the KBP Instrument Design Bureau of Tula, Russia. The weapon was designed with extreme short-range stopping power in mind for FSB urban combat units. The ASh-12 is a dedicated Urban Combat weapon for law enforcement operations, which must combine stopping power with limited penetration and a short range to avoid collateral damage to innocent bystandards.\n\nAmmo: 12.7x55mm STs-130\nMagazine Capacity: 10"
ITEM.model = "models/silver/outbreak/weapons/w_ash12.mdl"
ITEM.class = "cw_sil_ash12"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.price = 500000
ITEM.height = 2
ITEM.Range = 400
ITEM.Pen = 18
ITEM.Mag = 10
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 5.1
ITEM.flag = "A"
ITEM.barrel = "long"