ITEM.name = "PP-19 Bizon"
ITEM.description = "Russian submachine gun that fires 9x18mm Makarov."
ITEM.longdesc = "The PP-19 Bizon is a 9x18mm Makarov submachine gun developed in 1993 by the Russian company Izhmash, designed by a team of engineers headed by Victor Kalashnikov and Alexei Dragunov. The Bizon was developed at teh request of the Russian MVD and is primarily intended for counter-terrorist and law enforcement units that need fast and accurate fire at close ranges. The Bizon is isued to armed response units of the FSB and Ministry of Justice in Russia, and was used in combat operations against seperatists in Chechnya and Dagestan. The Bizon has largely been replaced by the PP-19-01 Vityaz in Russian service, which was developed directly from the design of the Bizon, due to reliability issues with the helical magazine.\n\nAmmo: 9x18mm\nMagazine Capacity: 64"
ITEM.model = "models/silver/outbreak/weapons/w_bizon.mdl"
ITEM.class = "cw_sil_bizon"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 12000 
ITEM.flag = "1"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 4
ITEM.weight = 2.1
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 50
ITEM.Pen = 6
ITEM.Mag = 64
ITEM.barrel = "medium"