ITEM.name = "M590"
ITEM.description = "The Mossberg 590 is a variant of the Mossberg 500 series, specifically made to be easier to field strip for cleaning, as well as being simpler to repair internal damage. Fires 12 Gauge shells."
ITEM.model = "models/weapons/ethereal/w_m590.mdl"
ITEM.class = "cw_sil_m590"
ITEM.weaponCategory = "secondary"
ITEM.width = 4
ITEM.height = 1
ITEM.price = 22000
ITEM.flag = "3"
ITEM.isWeapon = true 
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 3.3
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 8
ITEM.barrel = "medium"