ITEM.name = "CS-3a Combat Armor"
ITEM.model = "models/kek1ch/cs_heavy_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_cs3a.mdl"
ITEM.description= "A Clear Sky combat suit."
ITEM.longdesc = "This armor was created with a Soviet M32 rig and combat vest over a canvas bodysuit impregnated with Clear Sky's AIR-1 protective solution, providing a balance of anomaly and combat protection. It was built in early 2011 and saw limited use until production was increased in response to conflict with the Renegades, after which it became standard for Clear Sky assault squads.\n\nBallistic Protection:\nSkull: III\nNeck & Face: II\nTorso: III\nLimbs: II\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 140000
ITEM.flag = "4"
ITEM.br = 0.38
ITEM.fbr = 9
ITEM.ar = 0.4
ITEM.far = 4
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"3"}
ITEM.weight = 14
ITEM.maxArmor = 20
ITEM.res = {
	["Bullet"] = 0.2,
	["Blast"] = 0.2,
	["Fall"] = 0.2,
	["Burn"] = 0.2,
	["Radiation"] = 0.3,
	["Chemical"] = 0.2,
	["Shock"] = 0.2,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}