ITEM.name = "Gagarin-12 Armored Suit" 
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_gagarin.mdl"
ITEM.description= "A closed cycle combat suit." 
ITEM.longdesc = "The cutting edge of government protective technology in the Zone, this PSZ-13 bodysuit features high-quality ballistic protection with a closed cycle system and anomalous suppression device. This outfit was designed by the newly formed SIRCAA using lessons taken from expert stalkers and survivors of Operation Monolith to create a near-perfect protective suit for traversing the Zone. It is only just now being issued to select operatives in limited quantities, and has yet to be mass produced.\n\nBallistic Protection:\nSkull: III+\nNeck & Face: IIIA\nTorso: IIIA\nLimbs: IIIA\nWeight: 3"
ITEM.width = 2
ITEM.height = 3
ITEM.price = 550000
ITEM.flag = "A"
ITEM.br = 0.4
ITEM.fbr = 7
ITEM.ar = 0.5
ITEM.far = 2
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.artifactcontainers = {"3"}
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.noBusiness = true
ITEM.weight = 15
ITEM.maxArmor = 30
ITEM.res = {
	["Bullet"] = 0.3,
	["Blast"] = 0.3,
	["Fall"] = 0.3,
	["Burn"] = 0.3,
	["Radiation"] = 0.3,
	["Chemical"] = 0.3,
	["Shock"] = 0.3,
	["Psi"] = 0.3,
}

ITEM.newSkin = 0
ITEM.bodyGroups = {
	["chest armor"] = 1,
	["shoulderpads"] = 1,
	["closed-cycle"] = 1,
}