ITEM.name = "SRS-W \"Wolven\" "
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/silver/stalker/male_sunrise_merc.mdl"
ITEM.description= "A modified PSZ-9 suit used by Mercenaries." 
ITEM.longdesc = "This PSZ-9 is a creation for Blue Eagle by Freedom techs, either during the Alliance Wars or defecting ones afterward. It is intended for mercs whose tasks will see a fair amount of both anomaly interaction and light combat. \n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: III\nLimbs: II\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 75000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"3"}
ITEM.weight = 7
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.2,
	["Blast"] = 0.2,
	["Fall"] = 0.2,
	["Burn"] = 0.2,
	["Radiation"] = 0.2,
	["Chemical"] = 0.2,
	["Shock"] = 0.2,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}