ITEM.name = "12g Buckshot"
ITEM.model = "models/Items/BoxBuckshot.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "12 Gauge" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.price = 600
ITEM.description= "A box that contains %s 12 gauge shells. "
ITEM.longdesc = "Standard 12 gauge shell filled with 6 mm shot. Highly lethal at close range. Only suitable for use with smoothbore weapons."
ITEM.flag = "1"
ITEM.weight = 0.045
ITEM.isAmmo = true