ITEM.name = "Surgeon's Kit"
ITEM.model = "models/kek1ch/armor_repair_pro.mdl"
ITEM.longdesc = "A set of metal surgical instruments and means for field sterilization, as well as a pack of disposables. Enough to perform basic trauma surgeries in field conditions."
ITEM.description = "A kit for Surgical uses.."
ITEM.category = "Medical"
ITEM.flag = "1"
ITEM.price = 20000
ITEM.width = 1
ITEM.height = 1