ITEM.name = "SRS-E \"Eagle\" "
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_hawk_lone.mdl"
ITEM.description= "A twist on the standard mercenary suit."
ITEM.longdesc = "A variant of the Hawk suit, the Eagle sacrifices some of its secondary armors in exchange for better anomalous protection overall while keeping light.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: IIIA\nLimbs: IIA\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 25000
ITEM.flag = "1"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 5
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.1,
	["Blast"] = 0.1,
	["Fall"] = 0.1,
	["Burn"] = 0.2,
	["Radiation"] = 0.2,
	["Chemical"] = 0.1,
	["Shock"] = 0.1,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}