ITEM.name = "PSZ-9 Universal Protection" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_midnight_lone.mdl"
ITEM.description= "A Loner variant of the PSZ-9d suit." 
ITEM.longdesc = "This bodysuit was produced by one of Kiev's defense research institutes and was primarily commissioned by the Duty faction, who issue it as their standard uniform. Its use of cutting-edge materials provides decent protection against low-calibre firearms. Meanwhile, it provides adequate protection against anomalies, making it a well-rounded suit.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: III\nLimbs: IIA\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 40000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 7
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.1,
	["Blast"] = 0.1,
	["Fall"] = 0.1,
	["Burn"] = 0.2,
	["Radiation"] = 0.2,
	["Chemical"] = 0.2,
	["Shock"] = 0.2,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}