ITEM.name = "RS-4a Heavy Assault Armor"
ITEM.model = "models/kek1ch/cs_heavy_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_cs3b.mdl"
ITEM.description = "A haphazard Renegade assault suit."
ITEM.longdesc = "A set of assault armor made from a salvaged CS-3B suit, put together by Renegades as a frantic last ditch effort to fight back as their faction war turned against them. While retaining some key armoring of its origonal, it is a shallow imitation overall. \n\nBallistic Protection:\nSkull: III\nNeck & Face: IIIA\nTorso: IV\nLimbs: IIIA\nWeight: 4"
ITEM.width = 2
ITEM.height = 3
ITEM.price = 180000
ITEM.flag = "A"
ITEM.br = 0.5
ITEM.fbr = 5
ITEM.ar = 0.4
ITEM.far = 4
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"0"}
ITEM.noBusiness = true
ITEM.weight = 20
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0.1,
	["Radiation"] = 0.3,
	["Chemical"] = 0.2,
	["Shock"] = 0.1,
	["Psi"] = 0.0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}