CustomizableWeaponry:addFireSound("CW_KK_INS2_DOI_G43_FIRE", "weapons/g43/g43_fp.wav", 1, 105, CHAN_STATIC)

-- CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_wat?", "weapons/g43/handling/g43_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_BOLTBACK", "weapons/g43/handling/g43_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_BOLTRELEASE", "weapons/g43/handling/g43_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_EMPTY", "weapons/g43/handling/g43_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_FETCHMAG", "weapons/g43/handling/g43_fetchmag.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_MAGIN", "weapons/g43/handling/g43_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_MAGOUT", "weapons/g43/handling/g43_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_MAGRELEASE", "weapons/g43/handling/g43_magrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_DOI_G43_RATTLE", "weapons/g43/handling/g43_rattle.wav")
