CustomizableWeaponry:addFireSound("DOIVICKERS_FIRE", "weapons/doipack/vickers/vickers_fp.wav", 1, 100, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOIVICKERS_BELTALIGN", "weapons/doipack/vickers/handling/vickers_beltalign.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_BELTDROP", "weapons/doipack/vickers/handling/vickers_beltdrop.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_BELTJINGLE", "weapons/doipack/vickers/handling/vickers_beltjingle.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_BELTPULL", "weapons/doipack/vickers/handling/vickers_beltpull.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_BOLTBACK", "weapons/doipack/vickers/handling/vickers_boltback.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_BOLTRELEASE", "weapons/doipack/vickers/handling/vickers_boltrelease.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_DEPLOYGROUNDHIT", "weapons/doipack/vickers/handling/vickers_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_EMPTY", "weapons/doipack/vickers/handling/vickers_empty.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_FETCHMAG", "weapons/doipack/vickers/handling/vickers_fetchmag.wav")
CustomizableWeaponry:addReloadSound("DOIVICKERS_SHOULDER", "weapons/doipack/vickers/handling/vickers_shoulder_weapon.wav")
