ITEM.name = "Duty Heavy Motors and Shield"
ITEM.model = "models/kek1ch/safe_container.mdl"
ITEM.description = "A very rare upgrade for Exoskeletons created by the Duty Faction."
ITEM.longdesc = "A set of improved, hardened servos that includes a mounting point on either arm (intended to be your non dominant hand) for a large steel shield that offers III+ protection. The shield is not affected by Staggers or Stuns and must be penetrated to be defeated.\nIncreases servo carry weight\nIII+ ballistic shield and its mounting bracket"
ITEM.category = "Parts"
ITEM.flag = "A"
ITEM.price = 250000
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 8