ITEM.name = "Ecologist Supply Drop (SSP-99M)"
ITEM.model = "models/kek1ch/case.mdl"
ITEM.description = "A case with government markings. Four of these and an SSP99 could result in something useful."
ITEM.category = "Parts"
ITEM.flag = "A"
ITEM.price = 4000
ITEM.width = 2
ITEM.height = 2
ITEM.weight = 1