ITEM.name = "Overwatch Standard Issue Pulse Rifle"
ITEM.description = "Standard model Pulse Rifle."
ITEM.longdesc = "The Pulse Rifle is a combination of human firearm concepts - feeding ammo from a box magazine, but utilizing the Combine's dark energy technology to make an effective ranged weapon."
ITEM.model = "models/ez2models/weapons/w_irifle.mdl"
ITEM.weaponCategory = "primary"
ITEM.class = "cw_ar2"
ITEM.width = 4
ITEM.price = 50000
ITEM.height = 2
ITEM.Range = 100
ITEM.Pen = 15
ITEM.Mag = 30
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 5.2
ITEM.flag = "4"
ITEM.barrel = "medium"