ITEM.name = "AEK-919k"
ITEM.description = "A Russian submachine gun. Fires 9x18mm."
ITEM.longdesc = "The AEK-919K Kashtan is a Russian select-fire submachine gun, chambered for 9x18mm Makarov rounds, developed by the Kovrov Mechanical Plant"
ITEM.model = "models/silver/stalker/weapons/w_aek919k.mdl"
ITEM.class = "cw_sil_aek919k"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 4500
ITEM.flag = "1"
ITEM.isWeapon = true
ITEM.isPLWeapon = true 
ITEM.isCW = true
ITEM.modifier = 6
ITEM.weight = 1.8
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 20
ITEM.barrel = "short"