ITEM.name = "Bren L4 LMG"
ITEM.description= "A strange looking Automatic."
ITEM.longdesc = "The BREN Light Machine Gun was of French origin. It was developed and widely used by multiple countries during World War 2. Nowadays only cheap Chinese remakes litter the Earth, chambered in 7.62x39mm. This one however seems to be a bit more Western, and is chambered in 7.62 NATO.  \n\nAmmo: 7.62x51mm \nMagazine Capacity: 30"
ITEM.model = "models/khrcw2/doipack/w_bren.mdl"
ITEM.class = "doi_atow_bren"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.price = 100
ITEM.height = 2
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 6
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 5.2
ITEM.flag = "4"
ITEM.barrel = "long"