ITEM.name = "OTs-14 4A Groza"
ITEM.description= "A soviet-designed bullpup assault rifle chambered for 9x39mm."
ITEM.longdesc = "The OTs-14 4A Groza is a Russian selective fire bullpup assault rifle chambered for the 9×39mm round. It was developed in the 1990s at the TsKIB SOO (Central Design and Research Bureau of Sporting and Hunting Arms) in Tula, Russia.\n\nAmmo: 9x39mm\nMagazine Capacity: 30"
ITEM.model = "models/weapons/ethereal/item_groza1.mdl"
ITEM.class = "cw_kk_ins2_groza4"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.price = 95000
ITEM.height = 2
ITEM.Range = 200
ITEM.Pen = 12
ITEM.Mag = 30
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 4
ITEM.weight = 4
ITEM.flag = "4"
ITEM.barrel = "medium"