ITEM.name = "GSh-18"
ITEM.description= "A Russian handgun that fires 9x19mm."
ITEM.longdesc = "The GSh-18 is a 9 mm semi-automatic pistol developed by the KBP Instrument Design Bureau in Tula during the 1990s. The pistol's name is derived from its designers (Gryazev and Shipunov) and its magazine capacity of 18 rounds.\n\nAmmo: 9x19mm\nMagazine Capacity: 18"
ITEM.model = "models/weapons/gsh18/w_gsh18.mdl"
ITEM.class = "cw_sil_gsh18"
ITEM.weaponCategory = "sidearm"
ITEM.width = 2
ITEM.price = 4250
ITEM.height = 1
ITEM.flag = "3"
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 18
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 0.590
ITEM.barrel = "short"