ITEM.name = "L85A2"
ITEM.description= "A bullpup assault rifle. Fires 5.56x45mm."
ITEM.longdesc = "The standard rifle for the British armed forces. This rifle was designed to be fitted with various attachments.\n\nAmmo: 5.56x45mm\nMagazine Capacity: 30"
ITEM.model = "models/weapons/ethereal/w_l85a2.mdl"
ITEM.class = "cw_sil_l85a2"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.price = 28000
ITEM.height = 2
ITEM.flag = "3"
ITEM.Range = 150 
ITEM.Pen = 12
ITEM.Mag = 30
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 3.82
ITEM.barrel = "long"
ITEM.exRender = true
ITEM.iconCam = {
	pos = Vector(11.5, 200, 3),
	ang = Angle(0, 270, 0),
	fov = 10,
}