ITEM.name = "M240B"
ITEM.description = "The M240 has been used by the United States Armed Forces since the late 1970s. It is used extensively by infantry, most often in rifle companies, as well as on ground vehicles, watercraft and aircraft. Despite being heavier than some comparable weapons it is highly regarded for reliability and its standardization among NATO members is a major advantage. Fires 7.62x51 Rounds from Belts."
ITEM.model = "models/weapons/m240b/w_m249.mdl"
ITEM.class = "cw_sil_m240"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.height = 3
ITEM.price = 310000
ITEM.flag = "A"
ITEM.isWeapon = true 
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 5
ITEM.weight = 12.5
ITEM.Range = 150
ITEM.Pen = 18
ITEM.Mag = 100
ITEM.barrel = "short"