ITEM.name = "MP-153"
ITEM.description = "The MP-153 is a Russian semi-automatic shotgun developed in the late 1990s from the IZh-81M."
ITEM.model = "models/silver/outbreak/weapons/w_mp153_new.mdl"
ITEM.class = "cw_sil_mp153"
ITEM.weaponCategory = "secondary"
ITEM.width = 4
ITEM.height = 1
ITEM.price = 31000 
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 3.5
ITEM.flag = "4"
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 4
ITEM.barrel = "medium"