ITEM.name = "M1014"
ITEM.description = "Italian semi-automatic shotgun chambered for 12 Gauge."
ITEM.longdesc = "The Benelli M4 is a semi-automatic shotgun produced by Italian firearm manufacturer Benelli Armi SpA, and the last of Benelli's Super 90 series of semi-automatic shotguns.\nThe M4 uses a proprietary action design called the auto-regulating gas-operated (ARGO) system, which was created specifically for the weapon.\nThe weapon was designed in 1998, and was adopted by the armed forces of Italy, the United States, United Kingdom, among others, and has been used in a variety of conflicts, leading up to the present day.\n\nAmmo: 12 Gauge \nCapacity: 8"
ITEM.model = "models/weapons/m1014/w_m1014.mdl"
ITEM.class = "cw_sil_m1014"
ITEM.weaponCategory = "secondary"
ITEM.width = 4
ITEM.height = 1
ITEM.price = 35000
ITEM.flag = "3" 
ITEM.isWeapon = true 
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 3.8
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 8
ITEM.barrel = "medium"