ITEM.name = "PKM"
ITEM.description = "The PK is a belt-fed general-purpose machine gun chambered for the 7.62x54mmR rimmed cartridge. It was designed in the Soviet Union, and is currently in production in Russia, the original PK machine gun was introduced in 1961 and the improved PKM variant was introduced in 1969. The PKM was designed to replace the SGM and RP-46 machine guns that were previously in Soviet service. Uses 7.62x54mmR Belts."
ITEM.model = "models/weapons/w_mach_pkmbenis.mdl"
ITEM.class = "cw_sil_pkm"
ITEM.weaponCategory = "primary "
ITEM.width = 4
ITEM.height = 3
ITEM.price = 320000
ITEM.flag = "A"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 5
ITEM.weight = 9.0
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 150
ITEM.Pen = 18
ITEM.Mag = 100
ITEM.barrel = "medium"