ITEM.name = "CZ Scorpion EVO3"
ITEM.description = "The Scorpion EVO 3 is a 9mm carbine manufactured by Česká zbrojovka Uherský Brod, the select-fire variant designated as A1 being a submachine gun and the semi-automatic variant designated as S1. The EVO 3 designation denotes that the firearm is a third generation of CZ's line of small submachine guns started by the Škorpion vz. 61. Despite the name, it is mechanically unrelated to the Skorpion vz. 61."
ITEM.model = "models/weapons/ethereal/w_scorpion.mdl"
ITEM.class = "cw_sil_scorpion"
ITEM.weaponCategory = "secondary"
ITEM.width = 3
ITEM.height = 2
ITEM.price = 16000
ITEM.flag = "3"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true 
ITEM.modifier = 4
ITEM.weight = 2.4
ITEM.Range = 50
ITEM.Pen = 6
ITEM.Mag = 30
ITEM.barrel = "medium"