ITEM.name = "STG-44"
ITEM.description= "An old, automatic rifle."
ITEM.longdesc = "The STG-44 was a German-Produced Assault rifle during World War 2. Nowadays the design borders on extinction with how rare they are in the world, and with how exotic its ammunition is, owning one is more of a Novelty for Outlanders. Still, it's an automatic rifle and perhaps you'll find cartridges here and there.  \n\nAmmo: 7.62x33 \nMagazine Capacity: 25"
ITEM.model = "models/khrcw2/doipack/w_stg44.mdl"
ITEM.class = "doi_atow_stg44"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.price = 100
ITEM.height = 2
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 6
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 5.2
ITEM.flag = "4"
ITEM.barrel = "medium"