ITEM.name = "Sawed Off Izh-43"
ITEM.description = "The Izh-43 is a double barrel, breech-loading shotgun built primarily for hunting small to medium game. It has seen extensive use in The Zone due to its high availability and exceptional durability and simplicity. Fires 12 Gauge Shells. This particular one has had the barrels shortened significantly, resulting in higher recoil but easier use in close quarters. Brace for impact."
ITEM.model = "models/weapons/ethereal/w_sawnoff_db.mdl"
ITEM.class = "cw_sil_toz66_sawed"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 3000
ITEM.flag = "1"
ITEM.isWeapon = true
ITEM.isPLWeapon = true 
ITEM.isCW = true
ITEM.modifier = 12
ITEM.weight = 1.9
ITEM.Range = 30
ITEM.Pen = 2
ITEM.Mag = 2
ITEM.barrel = "short"