ITEM.name = "Toz-106"
ITEM.description = "The TOZ-106 is a small, lightweight bolt-action shotgun produced and sold by Tulsky Oruzheiny Zavod. It features a metal stockthat folds underneath the weapon in order to make it more compact, and a pistol grip. The rest of the stock is wooden. This shotgun was officially marketed as a hunting shotgun, but became popular among farmers, adventurers, travelers, campers, truck drivers and other people who needed a self-defense weapon for use in the countryside or wilderness. It received a lukewarm welcome among hunters, though it is somewhat popular for finishing wounded game."
ITEM.model = "models/silver/stalker/weapons/w_toz106.mdl"
ITEM.class = "cw_sil_toz106"
ITEM.weaponCategory = "secondary"
ITEM.width = 3
ITEM.height = 1
ITEM.price = 4000
ITEM.flag = "3"
ITEM.isWeapon = true 
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 2.5
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 4
ITEM.barrel = "medium"