ITEM.name = "Scrap Welrod Pistol"
ITEM.description= "An Outlands-Engineered firearm. Fires 9x19."
ITEM.longdesc = "This spec of Outlander ingenuity was originally birthed from a design created by Major Hugh Reeves of the British Inter-Servies Research Bureau during the Second World War. The Welrod pistol was produced for the sole purpose of supplying Resistance units in German-Occupied territories a means of assassination of German Soldiers and Officers. Cheap and low-quality, this bolt-action pistol is found to be of similar use today in the Union's many, oppressed Cities. \n\nAmmo: 9x19 \nMagazine Capacity: 6"
ITEM.model = "models/tnb/weapons/w_welrod.mdl"
ITEM.class = "doi_atow_welrod"
ITEM.weaponCategory = "secondary"
ITEM.width = 1
ITEM.price = 100
ITEM.height = 1
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 6
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 5.2
ITEM.flag = "4"
ITEM.barrel = "short"