CustomizableWeaponry:addFireSound("CW_SIL_TOZ34_FIRE", 				"weapons/toz/toz34_fire.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_M590_FIRE_SUPPRESSED", 	"weapons/m590/m590_suppressed_fp.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M590_EMPTY", 		"weapons/m590/handling/m590_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_BREAKOPEN", 	"weapons/toz66/breakopen.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_BREAKCLOSE", 	"weapons/toz66/breakclose.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_SHELLEJECT1", 	"weapons/toz66/shelleject1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_SHELLSEJECT", 	"weapons/toz66/shellseject.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_SHELLGRAB", 	"weapons/toz66/shellgrab.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_SHELLGRAB1", 	"weapons/toz66/shellgrab1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_SHELLINSERT1", 	"weapons/toz66/shellinsert1.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_TOZ_SHELLINSERT2", 	"weapons/toz66/shellinsert2.wav")