ITEM.name = "Artifice"
ITEM.model = "models/predatorcz/stalker/artifacts/electra_green.mdl"
ITEM.description = "A greenish ball with a crystal-like sheen."
ITEM.longdesc = "The Artifice is a newly formed thermally-based rock that emits a great deal of heat, making it very difficult for those carrying one to traverse hot areas, however it allows the user to carry greater loads through some unknown manner. Emits above average levels of radiation.\n\nWeight -3 (8kg)\nThermal -4\nRads +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 10000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 3
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}