ITEM.name = "Bastard"
ITEM.model = "models/artefacts/plenka.mdl"
ITEM.description = "A green ball of energy"
ITEM.longdesc = "The Bastard found its name at the hands of hapless bandits who confused it for a Jellyfish. Upon further examination, it seems the Bastard itself is in fact a faulty or mutated Jellyfish, having lost it's radiation-removing abilities. In exchange however, it gained the interesting dual abilities to diffuse electric shocks from the sheer radioactive build-up, and absorb lesser amounts of heat, which is then transferred into the artifact container's lining itself, to no harm.\nElectrical +3p\nThermal +1p\nRads +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.30,
	["Burn"] = 0.10,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}