ITEM.name = "Battery"
ITEM.model = "models/nasca/etherealsrp_artifacts/battery.mdl"
ITEM.description = "An electric artifact."
ITEM.longdesc = "The composition of this artifact includes dielectric elements, though the conditions of its formation remain unidentified by science. It is observed to make its user feel energized, though prolonged use is tiring.\n\nRads +1\nMovement +1s\nElectric -1"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.buff = "end"
ITEM.buffval = 2
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.weight = 0.4