ITEM.name = "Colony"
ITEM.model = "models/artefacts/yoyo.mdl"
ITEM.description = "A red bulbous bacterial growth"
ITEM.longdesc = "The result of two similar-but-ecologically-different bacterial colonies ending up in perfect symbiosis amidst a chemical environment, the two bacteria types eventually developing a sort of 'bridge'. This bridge, in fact, is the way the two bacteria, which inhabit a pseudo-organic disk-like plate, interact with one another; one absorbs poisonous chemicals and turns them into highly-condensed oxygen after digestion, while this second bacteria takes the condensed oxygen and turns it into carbon dioxide, which is then dispersed in limited and relatively harmless quantities. Due to this nature, the Colony can 'gorge' on additional hazardous chemicals when worn in a container. However, given the bacteria, do not hold up well at all when dangerous levels of electrical energy is introduced, and the chemicals involved make for fantastic conductors.\n\nChemical +3\nElectrical -2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 9500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.8
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.30,
	["Psi"] = 0.00,
}