ITEM.name = "Disk"
ITEM.model = "models/predatorcz/stalker/artifacts/dummy_dummy.mdl"
ITEM.description = "A crystalline colored thick Disk, almost looks like a frisbee."
ITEM.longdesc = "When used, the user is able to expend themselves at twice the normal rate, their metabolism and natural healing is increased by double. The physical exertions of the user are also doubled such as running, fighting, etc. In return the user gets short-term insomnia and dehydrates faster.\n\nHealing +2\nMovement +2s"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 300000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.buff = "heal"
ITEM.buffval = 2
ITEM.weight = 2