ITEM.name = "Furnace"
ITEM.model = "models/tnb/stalker/artifacts/gravi.mdl"
ITEM.description = "A formation in the shape of a sphere with an ashen exterior."
ITEM.longdesc = "At random points on the artifact's body the exterior will crumble away to expose a small internal flame before reforming. The flame inside absorbs heat remarkably well, though it never grows beyond the cool exterior that contains it.\n\nRads +2\nThermal +4"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 35000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.40,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 0.3