ITEM.name = "Humidifier"
ITEM.model = "models/artefacts/grib.mdl"
ITEM.description = "A small, clay-like orb."
ITEM.longdesc = "Clay-like orb with a top that frequently comes open as a result of internal pressure, spraying steam at a high velocity, quickly filling the air with extreme amounts of moisture that render most electronics inert. Surprisingly cool to the touch on the outside, and the rhythmic spraying is often times used by Stalkers as a sleep aid. \n\nThermal +2\nElectrical -4\nEMP Within 5 meter radius"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2100
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.20,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}