ITEM.name = "Kryptonite"
ITEM.model ="models/artefacts/emerald.mdl"
ITEM.description = "A green crystal formation."
ITEM.longdesc = "A green crystal formation that grows exclusively in chemical fields, nicknamed ‘Kryptonite’ by the stalkers who have discovered it, this green rock protects from harmful chemicals in the same way the Crystal protects from heat, albeit better, and at the cost of one’s physical abilities. \n\n+3p Chemical\n-4s Movement\n -2 Impact"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7500 
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}