ITEM.name = "Moonlight"
ITEM.model = "models/nasca/etherealsrp_artifacts/moonlight.mdl"
ITEM.description = "Light emits from this artifact."
ITEM.longdesc = "A glowing, almost perfectly spherical formation originating from electrical anomalies, this artifact resonates under the influence of psi waves. Through fine-tuning, it resonates in the opposite phase to psi waves, serving to neutralize them in the process.\n\nRads +2\nPsi +4"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 75000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 3
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.40,
}