ITEM.name = "Scorched"
ITEM.model = "models/srp/items/art_stoneflower.mdl"
ITEM.description = "An artifact covered in scorch marks."
ITEM.longdesc = "An artifact covered in scorch marks believed by many stalkers to be a cursed object, it is often ignored when discovered in a field. The rumor concerning this artifact originated from one of the two men who discovered it, which, if it is to be believed, causes baldness in people of any and all ages. \n\nThermal +1p\nRads -1\nChemical -2\nElectricity -1"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.5
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}