ITEM.name = "Stone Skin"
ITEM.model = "models/artefacts/signet.mdl"
ITEM.description = "A small, mundane looking stone."
ITEM.longdesc = "The artifact looks very mundane. On first glance, it is easy to mistake this for a rock. When picked up, there is no discernible tactile sensation where skin makes. When in use, deliberately closing your eyes for a few moments covers your body in a layer of stone that can improve ballistic and blunt force trauma protection, but temporarily immobilizes you.  \n\nWhen Active:\nImpact +1 Tier, Max 4\nAll ballistic armor values below III become III\nCan activate in response to any perceived threat regardless of whose turn it is, Stuns you and makes you immobile upon activation until the following turn"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 39000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 5
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.30,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}