ITEM.name = "Soul"
ITEM.model ="models/nasca/etherealsrp_artifacts/soul.mdl"
ITEM.description = "Spherish, blue artifact."
ITEM.longdesc = "A rare artifact seemingly formed of organic materials, it nonetheless has a striking appearance. It increases the body's overall recovery rate from any sort of damage through unknown means, but does not accelerate the accumulation of toxins.\n\nRads +2\nHealing +2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.flag = "A"
ITEM.buff = "heal"
ITEM.buffval = 2
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 2.2