ITEM.name = "Slug"
ITEM.model ="models/nasca/etherealsrp_artifacts/slug.mdl"
ITEM.description = "Very slimey."
ITEM.longdesc = "This artifact forms in chemical anomalies. It is known that using it heightens the rate of coagulation in blood, though it renders the user susceptible to various types of burns.\n\nBleeding -2\nThermal -1\nChemical -1"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 5500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.buff = "woundheal"
ITEM.buffval = 2
ITEM.weight = 1.3
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = -0.10,
	["Radiation"] = 0.00,
	["Chemical"] = -0.10,
	["Psi"] = 0.00,
}