ITEM.name = "Sheet"
ITEM.model = "models/tnb/stalker/artifacts/static.mdl"
ITEM.description = "A web-like artifact."
ITEM.longdesc = "Web-like in appearance, this artifact can typically be found growing off of metal in electrically-charged anomalous environments like a type of moss, it absorbs radiation but touching it without the proper insulation will cause the holder to feel a severe shock.\n\nRads -2\nElectricity -3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.5
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}