ITEM.name = "Spike"
ITEM.model = "models/tnb/stalker/artifacts/wrenched.mdl"
ITEM.description = "A common rock formed out of bits of meat and metal."
ITEM.longdesc = "A common rock formed out of bits of meat and metal slamming into each other in narrow Gravitational fields, the aptly named Spike has a sharp, serrated edge that the more intelligent snork like to grab and use as weapons or butchering tools, when their teeth can’t quite manage the job.\n\nMovement +3s\nBleeding +2\nRads +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.40,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}