CustomizableWeaponry:addReloadSound("DOIMELEE_DRAW",{
"weapons/doipack/shared/melee/bayonet_draw_01.wav",
"weapons/doipack/shared/melee/bayonet_draw_02.wav",
"weapons/doipack/shared/melee/bayonet_draw_03.wav"})
CustomizableWeaponry:addReloadSound("DOIMELEE_SWING",{ 
"weapons/doipack/shared/melee/weapon_melee_01.wav",
"weapons/doipack/shared/melee/weapon_melee_02.wav",
"weapons/doipack/shared/melee/weapon_melee_03.wav",
"weapons/doipack/shared/melee/weapon_melee_04.wav",
"weapons/doipack/shared/melee/weapon_melee_05.wav",
"weapons/doipack/shared/melee/weapon_melee_06.wav"})
CustomizableWeaponry:addReloadSound("DOIMELEE_HITWORLD",{ 
"weapons/doipack/shared/melee/weapon_melee_hitworld_01.wav",
"weapons/doipack/shared/melee/weapon_melee_hitworld_02.wav"})
CustomizableWeaponry:addReloadSound("DOIMELEE_HITFLESH",{ 
"weapons/doipack/shared/melee/weapon_melee_hitflesh_01.wav",
"weapons/doipack/shared/melee/weapon_melee_hitflesh_02.wav",
"weapons/doipack/shared/melee/weapon_melee_hitflesh_03.wav",
"weapons/doipack/shared/melee/weapon_melee_hitflesh_04.wav"})
