CustomizableWeaponry:addFireSound("CW_SIL_ACR_FIRE", "weapons/acr/acr_fire.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_SIL_ACR_FIRE_SUPPRESSED", "weapons/acr/acr_fire_suppressed.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_BOLTBACK", "weapons/mk18/handling/mk18_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_BOLTRELEASE", "weapons/mk18/handling/mk18_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_EMPTY", "weapons/mk18/handling/mk18_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_FIRESELECT", "weapons/mk18/handling/mk18_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_HIT", "weapons/mk18/handling/mk18_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_MAGIN", "weapons/mk18/handling/mk18_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_MAGOUT", "weapons/mk18/handling/mk18_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_MK18_MAGRELEASE", "weapons/mk18/handling/mk18_magrelease.wav")
