ITEM.name = "M67 Grenade"
ITEM.model = ("models/weapons/ethereal/w_m67.mdl")
ITEM.description = "A M67 Grenade"
ITEM.class = "cw_kk_ins2_nade_m67"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8000
ITEM.flag = "3"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.4