ITEM.name = "M84 Stun Grenade"
ITEM.model = ("models/weapons/ethereal/w_m84.mdl")
ITEM.description = "A M84 Stun Grenade, it stuns people if you use it right."
ITEM.class = "cw_kk_ins2_nade_m84"
ITEM.weaponCategory = "secondary"
ITEM.isWeapon = true
ITEM.noAmmo = true
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.flag = "1"
ITEM.category = "Weapons"
ITEM.isGrenade = true
ITEM.weight = 0.236