ITEM.name = "Black Light"
ITEM.model = "models/srp/items/spezzy/art_trystal.mdl"
ITEM.description = "An artifact somewhat resembling a Crystal."
ITEM.longdesc = "An off-shoot of the Crystal formation, the Black Light is the product of a rare phenomenon involving the heat of Thermals and the compression force of Gravis to form a strangely powerful defense against Psi, shining your light through it makes for a great makeshift dark light.\n\nPsy +6p"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 150000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.5
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.40,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}