ITEM.name = "Bubble"
ITEM.model ="models/nasca/etherealsrp_artifacts/bubble.mdl"
ITEM.description = "A green artifact."
ITEM.longdesc = "A compound composed of several hollow organic formations, this artifact emits a gaseous suvstance that is harmless to the body, but neutralizes radioactive particles within. It is highly effective, making it incredibly valuable to stalkers.\n\nRads -4"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 100000
ITEM.flag = "A"
ITEM.buff = "antirad"
ITEM.buffval = 4
ITEM.isArtefact = true
ITEM.weight = 0.7
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.40,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}