ITEM.name = "Blue Ring"
ITEM.model = "models/artefacts/setka.mdl"
ITEM.description = "Almost see-through, it has unmoving rings of blue on it."
ITEM.longdesc = "This artifact emits a field that psionically draws those suffering from phantom pains. The level of phantom pain determines how intense the attraction is. On contact with the skin, it emits a chemical that is capable of relieving phantom pain, including pain from current injuries. This chemical is also addictive so that it keeps the user using it for longer. As it is used, it shrinks. Eventually, as it shrinks and disappears, the area of the body in contact with it will also change color and material to match it.\n\nRads +4 (Unremovable)"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 200000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.debuff = "rads"
ITEM.debuffval = 4
ITEM.weight = 1.5