ITEM.name = "Core"
ITEM.model = "models/artefacts/sun.mdl"
ITEM.description = "An unusually cold object resembling a planet's core."
ITEM.longdesc = "Strangely cold to the touch, this artifact has the appearance of a planet’s heart, a yellow, slightly conductive liquid kept stabilized within its thick, earthy crust. Touching this liquid reveals it to be the source of the artifact’s low, low temperature. Emits radiation.\n\nThermal +2p\nElectricity -1\n Rads +1"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2700
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}