ITEM.name = "Crystal Flower"
ITEM.model = "models/artefacts/bud.mdl"
ITEM.description = "A corrupted Crystal, resembles a bouquet of spiky protrusions."
ITEM.longdesc = "This odd rock is the work of thermal and psionic anomalies clashing together, the formation itself emits twice the radiation a regular Crystal would, but has low psi-protective properties thrown into the mix.\n\nThermal +2p\nPsy +1p\nRads +2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 6500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.5
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.30,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}