ITEM.name = "Coil"
ITEM.model = "models/artefacts/itcher.mdl"
ITEM.description = "A heavy and oddly shaped artifact consisting of spirals with a single ball in the center."
ITEM.longdesc = "While worn, electrical currents travel through the user into the artifact, up the spiral formation and into the ball where they are harmlessly dispersed.\n\nRads +2\nElectrical +4"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.40,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 3.6