ITEM.name = "Dreamcatcher"
ITEM.model = "models/artefacts/peas.mdl"
ITEM.description = "A white ring with a white ornate shape bordering it."
ITEM.longdesc = " Holding onto this artifact immediately makes the user feel happy and calm. Stress free even. Those that touch the individual using it can feel the same, but the effect can only daisy chain up to five people. If one were to sleep with it above their head, their dreams would be extremely vivid and odd, but never bad. Extended use lessens and may even stop melatonin production, resulting in having no sense of a circadian rhythm and no fatigue prior to sleep.\n\nPsychologically addictive"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 130000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.40,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}