ITEM.name = "Death Lamp"
ITEM.model = "models/artefacts/deathlamp.mdl"
ITEM.description = "An artifact resembling a blooming flower."
ITEM.longdesc = "A unique artifact with a dreadful aura. The Zone’s greatest punishment for its greediest trespasser, the artifact resembles a large blooming flower, the core of which is an ominous red circle that stares at anyone daring enough to stare back. Never before has this artifact ever been seen or heard of, no rumors nor documents exist regarding the Death Lamp."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 0
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 3
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}