ITEM.name = "Firefly"
ITEM.model ="models/nasca/etherealsrp_artifacts/firefly.mdl"
ITEM.description = "Green and beautiful artifact."
ITEM.longdesc = "Interacting with energy fields unknown to science, this artifact considerably speeds up the regeneration of tissue and organs and normalizes metabolic processes. Fatally wounded stalkers can recover within seconds when exposed to this artifact, though it is extremely rare and radioactive.\n\nRads +3\nHealing +6"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 250000
ITEM.flag = "A"
ITEM.buff = "heal"
ITEM.buffval = 6
ITEM.debuff = "rads"
ITEM.debuffval = 3
ITEM.isArtefact = true
ITEM.weight = 2.5