ITEM.name = "Galaxy"
ITEM.model = "models/predatorcz/stalker/artifacts/glass.mdl"
ITEM.description = "A glowing ball of light and energy"
ITEM.longdesc = "A hypothetical artifact that simply should not, realistically, exist. The design itself of the artifact was created as a 'worst case scenario' for a thought experiment. However, after this experiment was conducted, similar items began to be found, albeit extremely rarely, in spatial anomalies by the rare few Stalkers who survive them.\n\nA ball of unknown metallic make surrounding an energy profile that is unknown to modern science. All known instances of this have been rendered inert after only a few moments outside of a Spatial Anomaly. Small portals jet out of the instances' crust, absorbing electricity and radiation with seemingly no upper limit, and the object itself is extraordinarily heavy.\nIt is hypothesized that a proper 'Galaxy' would be totally self-sufficient, and all the pores on it's 'shell' would be capable of producing portals soas to absorb energy of electric or radioactive means in a small area, while also by proxy intaking excess heat. Strangely, psi and spatial anomalies react violently in the presence of this artifact, with Space Bubbles often trying to expand to engulf said artifact. Any psi energy directed at the user by a psychic mutant is pinpoint, and several times more lethal.\nElectrical +8\nRads -6\nThermal +6\nPsi -6\nSpacial anomalies react violently\nReduces movement to 1/4th of standard."
ITEM.width = 3
ITEM.height = 3
ITEM.price = 275000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 25
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.80,
	["Burn"] = 0.60,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}