ITEM.name = "Gravi"
ITEM.model = "models/nasca/etherealsrp_artifacts/gravi.mdl"
ITEM.description = "Lumpy, reddish artifact."
ITEM.longdesc = "This artifact forms from metallic substances exposed to gravitational anomalies for prolonged periods. It has an antigravitational field around it, reducing the weight of the user's equipment by a noticeable degree.\n\nRads +2\nWeight -3 (+8kg)"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 24000
ITEM.flag = "A" 
ITEM.buff = "weight"
ITEM.buffval = 8
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 0.85