ITEM.name = "Growth"
ITEM.model = "models/artefacts/ear.mdl"
ITEM.description = "A small bundle of pulsating flesh."
ITEM.longdesc = "A small, pulsating flesh growth that shows all the signs of being alive without actually being so, grows out of meat lumps which themselves grow in isolated heat anomalies located underground. Can occasionally be found attached to frenzied mutants. \n\nStronger faster and tougher\nCauses a frienzy that leads to death"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 27000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}