ITEM.name = "Mama's Beads"
ITEM.model ="models/nasca/etherealsrp_artifacts/mamas_beads.mdl"
ITEM.description = "Helix-shaped, pulsating artifact."
ITEM.longdesc = "Though it is known to form in thermal anomalies, much about this artifact remains a mystery to scientists. Pulses in the thicker sections of the artifact force blood coming from open wounds to clot faster, increasing metabolism and forming a scab.\n\nBleedng -2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 32000
ITEM.flag = "A"
ITEM.buff = "woundheal"
ITEM.buffval = 1
ITEM.isArtefact = true
ITEM.weight = 1.3