ITEM.name = "Meat Chunk"
ITEM.model ="models/nasca/etherealsrp_artifacts/meatchunk.mdl"
ITEM.description = "Looks like flayed skin. Artifact."
ITEM.longdesc = "Formed in gravitational anomalies, this artifact is mostly organic and composed of fossilized and mutated animal tissue. When exposed to chemical contamination, it transforms harmful chemicals into a mucous fluid.\n\nRads +2\nChemical +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.30,
	["Psi"] = 0.00,
}
ITEM.weight = 2.4;