ITEM.name = "Mind"
ITEM.model = "models/artefacts/ameba.mdl"
ITEM.description = "An unusual, crystalline creation."
ITEM.longdesc = "A biproduct of an extremely specific anomalous environment in which choice minerals are hardened into crystalline formations, before being, through one way or another, electrified in a high voltage environment that creates a natural shock absorber within the center of the crystal, finalized by falling into a psi-heavy environment, in which the crystals seem to attune themselves to psi waves, naturally destabilizing and diffusing them. The process is painstakingly long, and through this time the Mind accumulates considerable radiation, and it is thermally unstable. \nPsi +3\nElectrical +3\nThermal -2\nRads +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 125000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}