ITEM.name = "Pearls"
ITEM.model = "models/artefacts/chelust.mdl"
ITEM.description = "A small string of beads."
ITEM.longdesc = "A string of hardened crystal beads, each about the size of a small pebble, highly resembles a pearl necklace minus the usual sheen given off by real pearls. Each individual bead seems to breathe like a lung. \n\n Able to hold your breath for longer\nProlonged use poisons the user"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 7750
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = .3
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}