ITEM.name = "Strand"
ITEM.model = "models/srp/items/art_mammasbeads.mdl"
ITEM.description = "An anomalous double-helix."
ITEM.longdesc = "Strands form out of dead bodies in chem-fields, they all have the pungent smell of rot following them. Stalkers like to toss bodies in fields in an effort to harvest these artifacts en-masse, making the market for them quite saturated.\n\nBleeding -2\nRads +2\nChem -2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.8
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.40,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}