CustomizableWeaponry:addFireSound("DOIBAR_FIRE", "weapons/doipack/bar/bar_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOIBAR_BIPODDEPLOY", "weapons/doipack/bar/handling/bar_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_BIPODRETRACT", "weapons/doipack/bar/handling/bar_bipodretract.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_BOLTBACK", "weapons/doipack/bar/handling/bar_boltback.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_BOLTRELEASE", "weapons/doipack/bar/handling/bar_boltrelease.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_DEPLOYGROUNDHIT", "weapons/doipack/bar/handling/bar_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_EMPTY", "weapons/doipack/bar/handling/bar_empty.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_ENDDEPLOYEDRELOAD", "weapons/doipack/bar/handling/bar_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_FETCHMAG", "weapons/doipack/bar/handling/bar_fetchmag.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_FIRESELECT", "weapons/doipack/bar/handling/bar_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_MAGHIT", "weapons/doipack/bar/handling/bar_mag_hit.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_MAGIN", "weapons/doipack/bar/handling/bar_magin.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_MAGOUT", "weapons/doipack/bar/handling/bar_magout.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_MAGOUTRATTLE", "weapons/doipack/bar/handling/bar_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_MAGRELEASE", "weapons/doipack/bar/handling/bar_magrelease.wav")
CustomizableWeaponry:addReloadSound("DOIBAR_RATTLE", "weapons/doipack/bar/handling/bar_rattle.wav")