CustomizableWeaponry:addFireSound("DOIMG34_FIRE", "weapons/doipack/mg34/mg34_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOIMG34_BELTALIGN", "weapons/doipack/mg34/handling/mg34_beltalign.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_BIPODDEPLOY", "weapons/doipack/mg34/handling/mg34_bipoddeploy.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_BIPODRETRACT", "weapons/doipack/mg34/handling/mg34_bipodretract.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_BOLTBACK", "weapons/doipack/mg34/handling/mg34_boltback.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_BOLTRELEASE", "weapons/doipack/mg34/handling/mg34_boltrelease.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_COVERCLOSE", "weapons/doipack/mg34/handling/mg34_coverclose.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_COVEROPEN", "weapons/doipack/mg34/handling/mg34_coveropen.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_DEPLOYGROUNDHIT", "weapons/doipack/mg34/handling/mg34_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_EMPTY", "weapons/doipack/mg34/handling/mg34_empty.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_ENDDEPLOYEDRELOAD", "weapons/doipack/mg34/handling/mg34_enddeployedreload.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_FETCHMAG", "weapons/doipack/mg34/handling/mg34_mag_fetch.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_FIRESELECT", "weapons/doipack/mg34/handling/mg34_fireselect_1.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_MAGFETCH", "weapons/doipack/mg34/handling/mg34_mag_fetch.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_MAGHIT", "weapons/doipack/mg34/handling/mg34_maghit.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_MAGIN", "weapons/doipack/mg34/handling/mg34_magin.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_MAGOUT", "weapons/doipack/mg34/handling/mg34_magout.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_MAGOUTFULL", "weapons/doipack/mg34/handling/mg34_magout_full.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_MAGOUTRATTLE", "weapons/doipack/mg34/handling/mg34_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_MAGRELEASE", "weapons/doipack/mg34/handling/mg34_magrelease.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_RATTLE", "weapons/doipack/mg34/handling/mg34_rattle.wav")
CustomizableWeaponry:addReloadSound("DOIMG34_SHOULDERWEAPON", "weapons/doipack/mg34/handling/mg34_shoulder_weapon.wav")