ITEM.name = "Amygdala"
ITEM.model = "models/gibs/hgibs_rib.mdl"
ITEM.description = "An extremely light and brittle-feeling object that is somehow unbreakable. It's cool to the touch and shines quite brightly."
ITEM.longdesc = "This artifact is able to 'repair' psyches based on what it perceives from the mind of an individual. Its natural psy affinity can also absorb a decent amount of psy energy on behalf of its user, but doing so causes it to attract heat from the surrounding environment.\n\nThermal -2\nPsi +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 75000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.1
ITEM.res = {
	["Fall"] = 0,
	["Blast"] = 0,
	["Bullet"] = 0,
	["Shock"] = 0,
	["Burn"] = 0,
	["Radiation"] = 0,
	["Chemical"] = 0,
	["Psi"] = 0.3,
}