ITEM.name = "Backbone"
ITEM.model = "models/predatorcz/stalker/artifacts/psi_field.mdl"
ITEM.description = "A flaccid spine-like artifact."
ITEM.longdesc = "A flaccid spine-like artifact that stiffens upon contact with certain chemical agents, pretty viscous and has the property of periodically lowering the temperature of the surrounding air around itself. Emits radiation. \n\n+2p Chemical\n+2p Thermal\n +2 Rads"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 16000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}