ITEM.name = "Crystal Thorn"
ITEM.model = "models/nasca/etherealsrp_artifacts/crystal_thorn.mdl"
ITEM.description = "Pointy artifact."
ITEM.longdesc = "This artifact forms in Burnt Fuzz anomalies. Like its non-crystalline cousin, it draws radiation from its user through blood. It is known to have a relatively stable price on the artifact black market.\n\nRads -3\nBleeding +2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4000
ITEM.flag = "A"
ITEM.buff = "antirad"
ITEM.buffval = 3
ITEM.weight = 0.8
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.30,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}