ITEM.name = "Coral"
ITEM.model = "models/artefacts/sponge.mdl"
ITEM.description = "A purplish-brown rock with a pattern resembling coral."
ITEM.longdesc = "This artifact appears as a purplish-brown rock with coral-like patterns, and can easily be mistaken for an ordinary rock off the ground. It emits a slight amount of radiation, and appears to harden the user's skin against physical blows. Users report a feeling of increased burden, as if a polar opposite to the more common artifacts with a weight reduction field.  \n\nImpact +4\nRads +1\nWeight + 4"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 58000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.0
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}