ITEM.name = "Compass"
ITEM.model ="models/nasca/etherealsrp_artifacts/compass.mdl"
ITEM.description = "A sphere shaped artifact."
ITEM.longdesc = "This legendary artifact sometimes goes undiscovered for years. It is able to find gaps in even the most complex anomaly fields, allowing the user to traverse them with ease. Proper use of the artifact requires knowledge on how to properly handle it.\n\nRads +2\nThermal +2\nChemical +2\nElectrical +2\nPsi +2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 300000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.20,
	["Burn"] = 0.20,
	["Radiation"] = 0.00,
	["Chemical"] = 0.20,
	["Psi"] = 0.20,
}