ITEM.name = "Crater"
ITEM.model = "models/artefacts/mica.mdl"
ITEM.description = "A chunk of copper"
ITEM.longdesc = "The result of copper ore placed under severe gravitational stress, fusing with other materials and partially hardening into an odd combination of extremely compressed soil, minerals, and even the bones of unknown creatures. Largely considered dead weight and non-anomalous, a recent experiment by the Ecologists revealed the nature of it's ability; it's a wonderful conductor of electricity, which is then diffused safely inside the object. However, given the materials from which it is made and the plentiful radiation, it's quite radioactive.\n\nElectrical +3\nRads +2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 3650
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.5
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.30,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}