ITEM.name = "Focus"
ITEM.model = "models/artefacts/ameba.mdl"
ITEM.description = "A singular sphere of fine neuron-like pathways."
ITEM.longdesc = "A sphere consisting of thousands of tightly-wound fibres, compacted into a solid ball. Electricity can be seen humming at break-neck speed between these pathways, cascading light all over its surface. Likely of interest to neurologists. \n\nBonus to combat within 10m\n1.x5 shots\nDebuff to combat beyond 10m\n5 Turn Stun on equip or unequip"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 65000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.0