ITEM.name = "Freezer"
ITEM.model = "models/tnb/stalker/artifacts/glacier.mdl"
ITEM.description = "A white Crystal, cold to the touch."
ITEM.longdesc = "This anomalous beauty is formed in extremely low temperatures and is often used by traders and barmen as a means to keep food frozen.\n\nThermal +2p\nMovement -1, stacks every turn"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 1500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.5