ITEM.name = "Flame"
ITEM.model = "models/nasca/etherealsrp_artifacts/flame.mdl"
ITEM.description = "Flaming artifact."
ITEM.longdesc = "This artifact forms in anomalous areas of intense thermal activity. It produces powerful infrared emissions which intensify the metabolic processes of the user, closing wounds before their eyes. It is extremely rare and valuable.\n\nRads +2\nBleeding -4"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 60000
ITEM.flag = "A"
ITEM.buff = "woundheal"
ITEM.buffval = 3
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.weight = 0.9