ITEM.name = "Flash"
ITEM.model = "models/nasca/etherealsrp_artifacts/flash.mdl"
ITEM.description = "This artifact emits a lot of light."
ITEM.longdesc = "A favorite among collectors due to its appearance, this artifact is popular among collectors. This crystalized artifact absorbs up to 5,000 volts of electricity, which it can later discharge.\n\nRads +2\nElectrical +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.30,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 0.2