ITEM.name = "Haze"
ITEM.model = "models/artefacts/setka.mdl"
ITEM.description = "An object that appears as if constantly in motion. Very difficult to hold with one hand."
ITEM.longdesc = "The Haze, when held, appears to be rapidly moving in a manner that's difficult to control, giving off some warmth. Very fragile. \n\nDistorts user into a blur when moving depending on speed and duration\nDizzyness and Nausa upon coming to a stop depending on speed and how abrupt the stop is\n Elec -1"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 59000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.5