ITEM.name = "Kaleidoscope"
ITEM.model = "models/artefacts/claw.mdl"
ITEM.description = "An oddly shaped formation with a completely smooth, reflective surface."
ITEM.longdesc = "The images reflected shimmer with a fantastical array of colors, distorting and changing slightly. It is said to captivate those who behold it and is hard to break one's gaze from the exotic display.\n\nRads +2\nPsi +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 45000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.30,
}
ITEM.weight = 2.5