ITEM.name = "Magnets"
ITEM.model = "models/artefacts/blackspray.mdl"
ITEM.description = "A duo of stones."
ITEM.longdesc = "This artifact that appears to be easily able to break apart, maybe even wanting to be separated. Put together as like positive and negative magnets, appearing almost like two Droplets connected at the ends emitting a light shade of violet-blue.\n\nTelepathy 500mts"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 35000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.0