ITEM.name = "Pacifier"
ITEM.model = "models/hunter/plates/plate.mdl"
ITEM.description = "A small cube shaped artifact."
ITEM.longdesc = "An artifact vaguely shaped like a cube, has a hard, metallic exterior but shaking it reveals that the interior has some kind of liquid inside. \n\nIncreased passive focus\nClouds the mind in combat"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 6750
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}