ITEM.name = "Pellicle Test"
ITEM.model ="models/tnb/stalker/artifacts/witchesjelly.mdl"
ITEM.description = "Spherish, blue artifact."
ITEM.longdesc = "Many researchers believe this artifact should be incapable of forming in any natural environment. It emits a slightly acidic compound which seems to neutralize harmful chemicals. It is the first artifact to be reproduced in laboratory conditions.\n\nChemical +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 24000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 2.2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.30,
	["Psi"] = 0.00,
}