ITEM.name = "Phantom Star"
ITEM.model = "models/artefacts/phantom_star.mdl"
ITEM.description = "A dark purple artifact."
ITEM.longdesc = "Recently discovered in the central zone by amateur researchers, Phantom Star is recorded as one of the most radioactive entities in the zone and cannot be handled by hand without severe consequences. Not much is known about its effects or origins however researchers have reported a high decrease in psionic radiation within a metres radius.\n\nRads +4\nPsi +3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 37500
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 4
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.30,
}
ITEM.weight = 1.5