ITEM.name = "Sparkler"
ITEM.model ="models/nasca/etherealsrp_artifacts/sparkler.mdl"
ITEM.description = "Silky in appearance. Artifact."
ITEM.longdesc = "One of the most common artifacts with electrostatic properties, this artifact is nonetheless valued by scientists. It has the ability to smooth fluctuations in electric field density.\n\nRads +1\nElectrical +2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 2000
ITEM.flag = "A"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.20,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
ITEM.weight = 0.75