ITEM.name = "Wheel"
ITEM.model = "models/props/de_inferno/wall_lamp_ring.mdl"
ITEM.description = "A small wheel shaped rock."
ITEM.longdesc = "A wheel-shaped rock formation with a hole in the center, emits a small buzzing noise when held up close to one’s ears. \n\nGrants the user better balance.\nIncreases your momentum when falling."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 6500
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}