ITEM.name = "Weave"
ITEM.model = "models/artefacts/lighthouse.mdl"
ITEM.description = "A weave of glowing energy"
ITEM.longdesc = "It was long thought that Spatial anomalies produced little in the way of artifacts, and in truth this is the case, but with the discovery of the 'Weave' artifact, this is presumed to be less so. Composed of what can best be described as interwoven beams of hard light forced into place by the bizarre workings of a Spatial-heavy environment, the Weave is often times unable to be detected, even when it's signature is programmed into a detector. Inside a Spatial Anomaly Field, the Weave bounces in and out of the warped reality, and the reality that the Spatial Anomalies inhabit. However, once it is touched by a Stalker it seems 'anchored' in place in the physical realm. Studies of this artifact are all the rage in some of the southern labs, but with a lack of samples and the simple fact that the existence of hard light in of itself being a new proven concept means that little is understood beyond it's baser abilities.\n\nThe Weave is nearly indestructible, being able to withstand bullets, grenades, and other anomalous attacks with ease. However, few of these extend to the wielder. Instead, the artifact is capable of severely dampening the effects of psi on the wielder. However, because of it's construction, it is quite hot already, and additional thermal energy usually siphons off into connected bodies with unusual ease. Extraordinarily light.\nPsi +3\nThermal -2"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 36000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 0.2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.30,
}