CustomizableWeaponry:addFireSound("DOITHOMM1A1_FIRE", "weapons/doipack/m1a1/m1a1_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOITHOMM1A1_BOLTRELEASE", "weapons/doipack/m1a1/handling/m1a1_boltrelease.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_DRUMMAGFETCH", "weapons/doipack/m1a1/handling/m1a1_drum_mag_fetch.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_DRUMMAGHIT", "weapons/doipack/m1a1/handling/m1a1_drum_maghit.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_DRUMMAGIN", "weapons/doipack/m1a1/handling/m1a1_drum_magin.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_DRUMMAGOUT", "weapons/doipack/m1a1/handling/m1a1_drum_magout.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_DRUMMAGOUTRATTLE", "weapons/doipack/m1a1/handling/m1a1_drum_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_EMPTY", "weapons/doipack/m1a1/handling/m1a1_empty.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_MAGHIT", "weapons/doipack/m1a1/handling/m1a1_maghit.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_MAGIN", "weapons/doipack/m1a1/handling/m1a1_magin.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_MAGOUT", "weapons/doipack/m1a1/handling/m1a1_magout.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_MAGOUTRATTLE", "weapons/doipack/m1a1/handling/m1a1_magout_rattle.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_MAGRELEASE", "weapons/doipack/m1a1/handling/m1a1_magrelease.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_MAGTAP", "weapons/doipack/m1a1/handling/m1a1_magtap.wav")
CustomizableWeaponry:addReloadSound("DOITHOMM1A1_RATTLE", "weapons/doipack/m1a1/handling/m1a1_rattle.wav")