ITEM.name = "Beryl-1 Service Uniform" 
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_berill1.mdl"
ITEM.description= "A Berill-1 Suit." 
ITEM.longdesc = "A poor protective outfit contracted by government officials to the lowest bidder, this outfit is typically issued to conscripts and enlisted servicemen. It provides adequate protection from small arms fire. Although its overall combat protection is better than some less expensive stalker uniforms, it is still painfully inadequate for the Zone's conditions.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: II\nLimbs: IIA\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 12200
ITEM.flag = "1"
ITEM.br = 0.2
ITEM.fbr = 1
ITEM.ar = 0.1
ITEM.far = 1
ITEM.isArmor = true
ITEM.artifactcontainers = {"0"} 
ITEM.img = Material("vgui/hud/berill7.png")
ITEM.weight = 8
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.1,
	["Blast"] = 0.1,
	["Fall"] = 0.1,
	["Burn"] = 0,
	["Radiation"] = 0,
	["Chemical"] = 0,
	["Shock"] = 0,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}