ITEM.name = "\"Vulture\" Armored Bandit Suit" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/silver/stalker/male_sunrise_bandit.mdl"
ITEM.description = "An armored bandit suit." 
ITEM.longdesc = "A suit that is frequently only found in the hands of Bandit hitmen, or more experienced gangs who have lasted long enough to build up a stock of spare parts. This suit is comprised of parts from a wide variety of sources, most of which had to be modified to work together. Bandits often take personal attachment to these suits and will not part with them willingly.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: III\nLimbs: IIIA\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 45000
ITEM.flag = "A"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.img = Material("vgui/hud/ps5m.png")
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"1"}
ITEM.weight = 7
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.3,
	["Blast"] = 0.3,
	["Fall"] = 0.1,
	["Burn"] = 0,
	["Radiation"] = 0.2,
	["Chemical"] = 0.1,
	["Shock"] = 0.1,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}