ITEM.name = "\"Dusk\" Stalker Suit (Female)" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/silver/stalker/female_dusk_lone.mdl"
ITEM.description = "An armored stalker suit." 
ITEM.longdesc = "An overall upgrade over the Sunrise suit, the Dusk features enhanced protection in a firefight while also being surprisingly comfortable to wear. For this reason, it can be a favored choice among any stalker who needs a little more protection than what the average stalker suit can afford.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: III\nLimbs: II\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 28000
ITEM.flag = "3"
ITEM.br = 0.2
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.img = Material("vgui/hud/ps5m.png")
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 7
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.1,
	["Blast"] = 0.1,
	["Fall"] = 0.1,
	["Burn"] = 0.1,
	["Radiation"] = 0.1,
	["Chemical"] = 0.1,
	["Shock"] = 0.1,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}