ITEM.name = "PSZ-12d Combat Armor"
ITEM.model = "models/kek1ch/spec_sold_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_psz12d_lone.mdl"
ITEM.description= "A Loner variant of the prototype Spetsnaz armored suit used by Duty." 
ITEM.longdesc = "This armor consists of some of the earliest armor used by Duty within the Zone. The suit is capable of stopping many ballistic threats, however, this level of protection comes at the cost of its weight, bulkiness and virtually non-existent anomaly protection. It has a legendary reputation as the uniform of some of Duty's most prominent veterans.\n\nBallistic Protection:\nSkull: III+\nNeck & Face: IIIA\nTorso: IV\nLimbs: III\nWeight: 3"
ITEM.width = 2
ITEM.height = 3
ITEM.price = 230000
ITEM.flag = "4"
ITEM.br = 0.4
ITEM.fbr = 9
ITEM.ar = 0.15
ITEM.far = 2
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.noBusiness = false
ITEM.artifactcontainers = {"0"}
ITEM.weight = 9
ITEM.maxArmor = 40
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0.1,
	["Radiation"] = 0.2,
	["Chemical"] = 0.1,
	["Shock"] = 0.0,
	["Psi"] = 0.2,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}