ITEM.name = "Monolith Scientific Suit (Female)"
ITEM.model ="models/kek1ch/monolith_scientific_outfit.mdl"
ITEM.replacements ="models/silver/stalker/female_seva_mono.mdl"
ITEM.description= "A modified SEVA suit."
ITEM.longdesc = "This modified SEVA suit features the Monolith's signature bulletproof vest, providing greater protection in combat. This suit offers excellent all-around protection against the Zone's myriad threats. These suits are afforded to the Monolith's more experienced defenders, as well as those charged with defending or exploring underground laboratories.\n\nBallistic Protection:\nSkull: II\nNeck & Face: II\nTorso: III\nLimbs: II\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 150000
ITEM.flag = "4"
ITEM.br = 0.2
ITEM.fbr = 10
ITEM.ar = 0.6
ITEM.far = 6
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.radProt = 0.8
ITEM.overlayPath = "vgui/overlays/hud_sci"
ITEM.img = Material("vgui/hud/seva.png")
ITEM.noBusiness = true
ITEM.artifactcontainers = {"4"}
ITEM.weight = 10
ITEM.maxArmor = 20
ITEM.res = {
	["Bullet"] = 0.2,
	["Blast"] = 0.2,
	["Fall"] = 0.2,
	["Burn"] = 0.3,
	["Radiation"] = 0.4,
	["Chemical"] = 0.3,
	["Shock"] = 0.3,
	["Psi"] = 0.3,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}