ITEM.name = "Trenchcoat"
ITEM.model = "models/kek1ch/novice_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_trenchcoat.mdl"
ITEM.description= "A long overcoat."
ITEM.longdesc = "A long, thick overcoat. The protection offered by this apparel can vary tremendously depending on the tailor, but as a general rule it is only slightly less useless than the leather jacket. Still, many newer stalkers will swear by it simply because it looks cool.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: 0\nLimbs: 0\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 2250
ITEM.flag = "1"
ITEM.br = 0.05
ITEM.fbr = 3
ITEM.ar = 0.05
ITEM.far = 1
ITEM.repairCost = ITEM.price/100*1
ITEM.img = Material("vgui/hud/trenchcoat.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 4
ITEM.res = {
	["Bullet"] = 0,
	["Blast"] = 0,
	["Fall"] = 0,
	["Burn"] = 0,
	["Radiation"] = 0,
	["Chemical"] = 0,
	["Shock"] = 0,
	["Psi"] = 0,
}

ITEM.newSkin = 4
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}