ITEM.name = "9x39mm"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "9x39MM" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 9x39mm ammo. "
ITEM.longdesc = "The SP-5 is a subsonic 9x39mm rifle round with a bimetallic casing. The round contains a steel core with a gap behind it that is filled with lead. Requires a suppressor for stealth firing. Was used by special services of Warsaw Pact countries."
ITEM.price = 1600
ITEM.weight = 0.044
ITEM.isAmmo = true
ITEM.flag = "3"