CustomizableWeaponry:addFireSound("DOILEWIS_FIRE", "weapons/doipack/lewis/lewis_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOILEWIS_BOLTBACK", "weapons/doipack/lewis/handling/lewis_boltback.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_DEPLOYGROUNDHIT", "weapons/doipack/lewis/handling/lewis_deploygroundhit.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_EMPTY", "weapons/doipack/lewis/handling/lewis_empty.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_FETCHMAG", "weapons/doipack/lewis/handling/lewis_fetchmag.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_MAGFIDDLE", "weapons/doipack/lewis/handling/lewis_magfiddle.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_MAGHIT", "weapons/doipack/lewis/handling/lewis_maghit.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_MAGIN", "weapons/doipack/lewis/handling/lewis_magin.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_MAGOUT", "weapons/doipack/lewis/handling/lewis_magout.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_MAGOUTFULL", "weapons/doipack/lewis/handling/lewis_magoutfull.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_MAGRELEASE", "weapons/doipack/lewis/handling/lewis_magrelease.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_RATTLE", "weapons/doipack/lewis/handling/lewis_rattle.wav")
CustomizableWeaponry:addReloadSound("DOILEWIS_SHOULDERWEAPON", "weapons/doipack/lewis/handling/lewis_shoulder_weapon.wav")
