ITEM.name = "Lead Lined Container"
ITEM.model = "models/kek1ch/lead_box_closed.mdl"
ITEM.description = "A portable lead container with a sealed lid, could be used to store Artifacts or other Anomalous materials to restrict raditation."
ITEM.category = "Storage"
ITEM.flag = "1"
ITEM.price = 2500
ITEM.width = 1
ITEM.height = 2
ITEM.invWidth = 1
ITEM.invHeight = 1
ITEM.isBaggable = true