ITEM.name = "5.56x45mm Belt"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "5.56x45MMB"
ITEM.description = "A belt that contains %s rounds of 5.56x45mm."
ITEM.category = "Ammunition"
ITEM.price = 8000
ITEM.flag = "4"
ITEM.ammoAmount = 200
ITEM.weight = 0.039
ITEM.isAmmo = true