ITEM.name = "Altyn Helmet"
ITEM.description = "A Soviet-Era Helmet utilized by Spetsnaz and other Special-Forces within Russia. It features Titanium-Lined ballistic-armor, and an adjustable face-mask that carries ballistic protection as well.\n\nHead: IIIA\nFace: IIIA"
ITEM.category = "Upgrades"
ITEM.model = "models/shtokerbox/ground_headgear_atlyn.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 40000
ITEM.slot = 3
ITEM.flag = "A"
ITEM.isUpgrade = true
ITEM.weight = 0.05
ITEM.isHelmetUpg = true