ITEM.name = "Level IIA Kevlar Vest"
ITEM.description = "A Level IIA kevlar vest. Though considered outdated and not much in use even before the war, it's often better than nothing."
ITEM.category = "Upgrades"
ITEM.model = "models/armor/w_eq_armor.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 40000
ITEM.slot = 2
ITEM.flag = "A"
ITEM.isUpgrade = true
ITEM.isArmorUpg = true
ITEM.weight = 0.05
