CustomizableWeaponry:addReloadSound("DOIMELEE_SWING",{ 
"weapons/doipack/shared/melee/weapon_melee_01.wav",
"weapons/doipack/shared/melee/weapon_melee_02.wav",
"weapons/doipack/shared/melee/weapon_melee_03.wav",
"weapons/doipack/shared/melee/weapon_melee_04.wav",
"weapons/doipack/shared/melee/weapon_melee_05.wav",
"weapons/doipack/shared/melee/weapon_melee_06.wav"})
CustomizableWeaponry:addReloadSound("DOIETOOL_HITWORLD",{ 
"weapons/doipack/entrenchingtool/ent_tool_melee_01.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_02.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_03.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_04.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_05.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_06.wav"})
CustomizableWeaponry:addReloadSound("DOIETOOL_HITFLESH",{ 
"weapons/doipack/entrenchingtool/ent_tool_melee_001.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_002.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_003.wav",
"weapons/doipack/entrenchingtool/ent_tool_melee_004.wav"})
