ITEM.name = "7.62x39mm Belt"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x39MMB"
ITEM.description = "A belt and drum that contains %s rounds of 7.62x39mm."
ITEM.longdesc = "7.62x39 Full Metal Jacket is one the most commonly used types of ammunition, especially in Africa and in the Middle East. Some nicknamed it the 'Round of the Revolution' due to its favored use by both terrorist and criminal organizations. Due to the sheer power of the round most military organizations have turned to using additional steel plates to counter 7.62x39 as there is a high probability of encountering it in combat situations."
ITEM.category = "Ammunition"
ITEM.price = 4800
ITEM.flag = "4"
ITEM.ammoAmount = 100
ITEM.weight = 0.025
ITEM.isAmmo = true
