ITEM.name = "Moody"
ITEM.model = "models/spitball_medium.mdl"
ITEM.description = "A vaguely orb-shaped glass artifact with a sickly yellow tint."
ITEM.longdesc = "An unusual glassy orb with a notable yellow tint. Looking into the orb appears to amplify the emotions of those that stare into it, according to current mood."
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}