ITEM.name = "Puddle"
ITEM.model = "models/ethprops/consumable/flask_water.mdl"
ITEM.description = "A puddle."
ITEM.longdesc = "A shapeless, liquified artifact that oddly enough cannot be divided or separated, will always remain as one cohesive puddle regardless of the conditions it’s put through. Must be contained in a flask or other container. \n\nChemical Hotspot +3 Rounds\n\nThermal Hotspot +3 RoundsElectrical Hotspot -2\nSingle use"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8800
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.30,
	["Psi"] = 0.00,
}