ITEM.name = "Spring"
ITEM.description = "A brownish hybrid artifact."
ITEM.longdesc = "This artifact consists of two disks held together by an invisible force, believed to be formed from a fusion of a Battery and Shell artifact by scientists. It is known to produce a similarly invisible field around the wearer which helps to mitigate blunt trauma.\n\nImpact +4"
ITEM.category = "Artifacts"
ITEM.model = "models/srp/items/art_spring.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.5
ITEM.isArtefact = true
ITEM.price = 200000
ITEM.flag = "A"
ITEM.weight = 3.5
ITEM.res = {
	["Fall"] = 0.40,
	["Blast"] = 0.00,
	["Bullet"] = 0.40,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}