ITEM.name = "Shell"
ITEM.model = "models/nasca/etherealsrp_artifacts/shell.mdl"
ITEM.description = "Blue, semit-ransparent artifact."
ITEM.longdesc = "Formerly considered to be useless, this artifact was discovered to stimulate the nervous system when kept in constant contact with the body. It helps to replenish the energy of its user.\n\nRads +1\nMovement +2s\n Electric -1"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 16000
ITEM.flag = "A"
ITEM.buff = "end"
ITEM.buffval = 3
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.weight = 2