ITEM.name = "Sharpeye"
ITEM.model = "models/artefacts/dragon_eye.mdl"
ITEM.description = "A geometric round with a hazy, orange exterior and a singular core of yellow, taking on the appearance of a slit pupil from a reptile."
ITEM.longdesc = "This artifact is a bright formation often formed in a 'Enduring Dark' anomaly. It seems to follow the holder regardless of orientation. Its very presence demands the eyesight of those nearby - catching the eye with unusual frequency.\n\nNatural Night Vision\nRads Amplification"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 40000
ITEM.flag = "A"
ITEM.isArtefact = true
ITEM.weight = 1.0