ITEM.name = "Snowflake"
ITEM.model ="models/nasca/etherealsrp_artifacts/snowflake.mdl"
ITEM.description = "This artifact features blue spikes."
ITEM.longdesc = "Bearing a similar structure to the Kolobok, this artifact forms in electrical anomalies. It is known to have an electrostimulative effect which significantly improves the user's vitality and muscle tone.\n\nRads +1\nElectrical -1\nMovement +3s"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 24000
ITEM.flag = "A"
ITEM.buff = "end"
ITEM.buffval = 4
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.isArtefact = true
ITEM.weight = 3.2
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = -0.20,
	["Burn"] = 0.00,
	["Radiation"] = 0.00,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}
