ITEM.name = "Wrenched"
ITEM.model ="models/nasca/etherealsrp_artifacts/wrenched.mdl"
ITEM.description = "Bizarre, whalelike artifact."
ITEM.longdesc = "A strangely shaped artifact resulting from gravitational anomalies, this artifact acts as a sponge absorbing radioactive particles both from the environment and the body of its user.\n\nRads -3"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 30000
ITEM.flag = "A"
ITEM.buff = "antirad"
ITEM.buffval = 3
ITEM.isArtefact = true
ITEM.weight = 2.3
ITEM.res = {
	["Fall"] = 0.00,
	["Blast"] = 0.00,
	["Bullet"] = 0.00,
	["Shock"] = 0.00,
	["Burn"] = 0.00,
	["Radiation"] = 0.30,
	["Chemical"] = 0.00,
	["Psi"] = 0.00,
}