CustomizableWeaponry:addFireSound("DOIOWEN_FIRE", "weapons/doipack/owen/owen_fp.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOIOWEN_BOLTBACK", "weapons/doipack/owen/handling/owen_boltback.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_BOLTLOCK", "weapons/doipack/owen/handling/owen_boltlock.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_BOLTUNLOCK", "weapons/doipack/owen/handling/owen_boltunlock.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_FETCHMAG", "weapons/doipack/owen/handling/owen_fetchmag.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_MAGHIT", "weapons/doipack/owen/handling/owen_maghit.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_MAGIN", "weapons/doipack/owen/handling/owen_magin.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_MAGOUT", "weapons/doipack/owen/handling/owen_magout.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_MAGRELEASE", "weapons/doipack/owen/handling/owen_magrelease.wav")
CustomizableWeaponry:addReloadSound("DOIOWEN_RATTLE", "weapons/doipack/owen/handling/owen_rattle.wav")