ITEM.name = "SR-2 Veresk"
ITEM.description = "The SR-2 'Veresk' differs from most SMGs by its gas-operated action with rotating bolt, typically used in assault rifles (normally SMGs utilise different blowback principles). This design is partially borrowed from the SR-3 'Vikhr' compact assault rifle. Externally the 'Veresk' is similar to the Uzi; 20- or 30-round magazines are inserted into the pistol grip. There are two AK-style control levers on both sides of the receiver: the right one is the safety switch, the left is a fire-mode selector. Fires 9x21 Rounds."
ITEM.model = "models/weapons/ethereal/w_veresk.mdl"
ITEM.class = "cw_sil_veresk"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 50000
ITEM.flag = "4"
ITEM.isWeapon = true 
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 4
ITEM.weight = 1.65
ITEM.Range = 50
ITEM.Pen = 8
ITEM.Mag = 30
ITEM.barrel = "short"