ITEM.name = "Encrypted Solid-State Flash-Storage"
ITEM.model = "models/illusion/eftcontainers/flashstorage.mdl"
ITEM.description = "A piece of advanced technology."
ITEM.longdesc = "A state of the arc Flash-Storage Solid-State drive with Military-Grade encryption. Used by the SBU and Ecologists for keeping highly secretive information on a strict need-to-know basis."
ITEM.category = "Intel"
ITEM.flag = "4"
ITEM.price = 35000
ITEM.width = 2
ITEM.height = 1
