ITEM.name = "Gauss Batteries"
ITEM.model = "models/ethprops/ammo/gauss.mdl"
ITEM.ammo = "Batteries" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A battery for the Item 62 Gauss Rifle."
ITEM.longdesc = "Gauss rounds have perfect performance in nearly every metric - and above perfect notably in piercing and armor penetration, giving it the ability to completely ignore any body armour. In fact, Gauss rounds perform better against heavier armor, and along with some sniper rounds is one of the only munitions easily capable of killing multiple targets with one shot. Also they are able to kill the most dangerous mutants such as Chimera or Psueogiants in only a few shots. They consist of encapsulated pieces of the Flash artifact, which supply the energy required to propel the electromagnetic slugs at extreme velocities."
ITEM.price = 1000
ITEM.flag = "A"
ITEM.weight = 0.016
ITEM.isAmmo = true