ITEM.name = "Bandit Patch"
ITEM.model = "models/kek1ch/tfw_badge_bandit.mdl"
ITEM.description = "A patch that once belonged to a member of the Bandits faction."
ITEM.category = "factionpatches"
ITEM.width = 1
ITEM.height = 1
ITEM.price = "1650"
ITEM.flag = "1"
ITEM.weight = 3