CustomizableWeaponry:addFireSound("CW_SIL_L85A2_FIRE", "weapons/l85/l85_fire.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_KK_INS2_L85A2_FIRE_SUPPRESSED", "weapons/cw_kk_ins2_l85a2/fire_suppressed.wav", 1, 75, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_BOLTBACK", "weapons/m4a1/handling/m4a1_boltback.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_BOLTRELEASE", "weapons/m4a1/handling/m4a1_boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_EMPTY", "weapons/m4a1/handling/m4a1_empty.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_FIRESELECT", "weapons/m4a1/handling/m4a1_fireselect.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_HIT", "weapons/m4a1/handling/m4a1_hit.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGHITRELEASE", "weapons/m4a1/handling/m4a1_maghitrelease.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGIN", "weapons/m4a1/handling/m4a1_magin.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGOUT", "weapons/m4a1/handling/m4a1_magout.wav")
CustomizableWeaponry:addReloadSound("CW_KK_INS2_M4A1_MAGRELEASE", "weapons/m4a1/handling/m4a1_magrelease.wav")