ITEM.name ="CS-1 Scout Armor"
ITEM.model ="models/kek1ch/cs_light_outfit.mdl"
ITEM.replacements ="models/nasca/stalker/male_cs1a.mdl"
ITEM.description="A Clear Sky scouting suit."
ITEM.longdesc = "A light suit worn by Clear Sky's novice researchers, scouts and guides. It was designed for conducting scouting operations in areas of low anomalous activity. It is made of high quality, lightweight, waterproof materials and sports little combat protection.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: II\nLimbs: 0\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 13000
ITEM.flag = "1"
ITEM.br = 0.18
ITEM.fbr = 1
ITEM.ar = 0.15
ITEM.far = 1
ITEM.isArmor = true
ITEM.repairCost = ITEM.price/100*1
ITEM.img = Material("vgui/hud/cs1.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 4
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.1,
	["Blast"] = 0.1,
	["Fall"] = 0.1,
	["Burn"] = 0.1,
	["Radiation"] = 0.2,
	["Chemical"] = 0.2,
	["Shock"] = 0.1,
	["Psi"] = 0.1,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}