ITEM.name = "SAS-P \"Paladin\" "
ITEM.model = "models/kek1ch/exolight_outfit.mdl"
ITEM.replacements = "models/npc/stalker_merc/merc_metro/merc_metro.mdl"
ITEM.description = "A set of Paladin Assault Armor."
ITEM.longdesc = "The Mercenary answer to the Stingray, the Paladin is an older concept re-imagined using American-made armor parts intended for heavy combat in areas of low anomaly activity while still remaining mobile.\n\nBallistic Protection:\nSkull: III+\nNeck & Face: IIIA\nTorso: IV\nLimbs: III\nWeight: 3"
ITEM.width = 2
ITEM.height = 3
ITEM.price = 250000
ITEM.flag = "A"
ITEM.br = 0.6
ITEM.fbr = 11
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"2"}
ITEM.noBusiness = true
ITEM.weight = 10
ITEM.maxArmor = 30
ITEM.res = {
	["Bullet"] = 0.4,
	["Blast"] = 0.4,
	["Fall"] = 0.4,
	["Burn"] = 0.1,
	["Radiation"] = 0.2,
	["Chemical"] = 0.1,
	["Shock"] = 0.1,
	["Psi"] = 0.2,
}

ITEM.newSkin = 0