ITEM.name = "SAS-H \"Hawk\" "
ITEM.model ="models/kek1ch/merc_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_hawk_lone.mdl"
ITEM.description= "A standard mercenary suit."
ITEM.longdesc = "An older suit issued to the Blue Eagle faction, made from repurposed Western special forces kit. These days, it serves fine as a light duty scouting suit, but is poorly suited for the Zone in combat and anomalies both.  .\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: IIIA\nLimbs: II\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 25000
ITEM.flag = "1"
ITEM.br = 0.2
ITEM.fbr = 8
ITEM.ar = 0.05
ITEM.far = 1.5
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_merc"
ITEM.img = Material("vgui/hud/xm40.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 5
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.2,
	["Blast"] = 0.2,
	["Fall"] = 0.2,
	["Burn"] = 0.1,
	["Radiation"] = 0.1,
	["Chemical"] = 0,
	["Shock"] = 0,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}