ITEM.name = "R-2 Assault Armor"
ITEM.model ="models/kek1ch/cs_heavy_outfit.mdl"
ITEM.replacements ="models/silver/stalker/female_cs2_lone.mdl"
ITEM.description= "A Renegade assault suit."
ITEM.longdesc = "A Renegade suit made from a CS-2 for primarily combat duties, improving on its armor while suffering in its anomalous protection. \n\nBallistic Protection:\nSkull: IIIA\nNeck & Face: II\nTorso: III+\nLimbs: IIA\nWeight: 2"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 65000
ITEM.flag = "A"
ITEM.br = 0.28
ITEM.fbr = 8
ITEM.ar = 0.20
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isHelmet = true
ITEM.isArmor = true
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"0"}
ITEM.weight = 10
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.30,
	["Blast"] = 0.30,
	["Fall"] = 0.30,
	["Burn"] = 0.10,
	["Radiation"] = 0.10,
	["Chemical"] = 0.10,
	["Shock"] = 0.10,
	["Psi"] = 0.10,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}