ITEM.name = "\"Sunrise\" Stalker Suit"
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_sunrise_lone.mdl"
ITEM.description = "A standard stalker outfit."
ITEM.longdesc = "This DIY suit is made of twin-layered rubberised cloth with plexiglass lining and integrated body armor. It is the quintessential outfit of a stalker, and despite not being very protective, it enjoys immense popularity among rookies and veteran stalkers alike thanks to its economical use and great modification potential.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: II\nLimbs: IIA\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 10000
ITEM.flag = "1"
ITEM.br = 0.15
ITEM.fbr = 6
ITEM.ar = 0.15
ITEM.far = 2
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.repairCost = ITEM.price/100*1
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"2"}
ITEM.weight = 5
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.1,
	["Blast"] = 0.1,
	["Fall"] = 0.1,
	["Burn"] = 0.1,
	["Radiation"] = 0.1,
	["Chemical"] = 0.1,
	["Shock"] = 0.1,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}