ITEM.name = "Wind Suit" 
ITEM.model = "models/kek1ch/stalker_outfit.mdl"
ITEM.replacements = "models/nasca/stalker/male_wind_lone.mdl"
ITEM.description= "A Loner variant of the lightweight suit often used by Freedom." 
ITEM.longdesc = "This comfortable stalker bodysuit is made by Freedom craftsmen. The suit's fabric is treated with Horizon, a special solution developed by the faction by trial and error, to increase resistance to anomalies. It is standard among members of Freedom, who enjoy its light weight and anomaly protection to move through the Zone with ease.\n\nBallistic Protection:\nSkull: 0\nNeck & Face: 0\nTorso: IIIA\nLimbs: IIA\nWeight: 1"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 22000
ITEM.flag = "4"
ITEM.br = 0.1
ITEM.fbr = 7
ITEM.ar = 0.2
ITEM.far = 3
ITEM.isGasmask = true
ITEM.isArmor = true
ITEM.repairCost = ITEM.price/100*1
ITEM.overlayPath = "vgui/overlays/hud_gas"
ITEM.img = Material("vgui/hud/eo20.png")
ITEM.artifactcontainers = {"4"}
ITEM.weight = 4
ITEM.maxArmor = 10
ITEM.res = {
	["Bullet"] = 0.1,
	["Blast"] = 0.1,
	["Fall"] = 0.1,
	["Burn"] = 0.1,
	["Radiation"] = 0.2,
	["Chemical"] = 0.2,
	["Shock"] = 0.2,
	["Psi"] = 0,
}

ITEM.newSkin = 0
ITEM.bodygroup = {0}
ITEM.bodygroupsub = {0}