CustomizableWeaponry:addFireSound("DOIM1A1CAR_FIRE", "weapons/doipack/m1carbine_para/m1carbine_para_fp.wav", 1, 105, CHAN_STATIC)
CustomizableWeaponry:addFireSound("DOIM1A1CAR_FIRE_SUPPRESSED", "weapons/doipack/m1carbine_para/m1carbine_para_suppressed_fp.wav", 1, 80, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("DOIM1A1CAR_BOLTBACK", "weapons/doipack/m1carbine_para/handling/m1carbine_para_boltback.wav")
CustomizableWeaponry:addReloadSound("DOIM1A1CAR_BOLTRELEASE", "weapons/doipack/m1carbine_para/handling/m1carbine_para_boltrelease.wav")
CustomizableWeaponry:addReloadSound("DOIM1A1CAR_EMPTY", "weapons/doipack/m1carbine_para/handling/m1carbine_para_empty.wav")
CustomizableWeaponry:addReloadSound("DOIM1A1CAR_MAGIN", "weapons/doipack/m1carbine_para/handling/m1carbine_para_magin.wav")
CustomizableWeaponry:addReloadSound("DOIM1A1CAR_MAGOUT", "weapons/doipack/m1carbine_para/handling/m1carbine_para_magout.wav")
CustomizableWeaponry:addReloadSound("DOIM1A1CAR_MAGRELEASE", "weapons/doipack/m1carbine_para/handling/m1carbine_para_magrelease.wav")
CustomizableWeaponry:addReloadSound("DOIM1A1CAR_RATTLE", "weapons/doipack/m1carbine_para/handling/m1carbine_para_rattle.wav")