ITEM.name = "23x75mm Shrapnel"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "23mm Shell"
ITEM.description = "A Box that contains %s 23mm Shrapnel shells."
ITEM.category = "Ammunition"
ITEM.price = 1000
ITEM.flag = "4"
ITEM.ammoAmount = 10
ITEM.weight = 0.1
ITEM.isAmmo = true