ITEM.name = ".45 ACP Match Grade"
ITEM.model = "models/kek1ch/ammo_1143x23_fmj.mdl"
ITEM.ammo = ".45 ACP -MG-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of .45 ACP ammo. "
ITEM.longdesc = "The .45 caliber full metal jacket round has enjoyed popularity for a hundred years thanks to its ballistic performance and a relatively small propelling charge. As a result, the bullet in this round is relatively slow but highly accurate and provides considerable stopping power. These ones have been made to a higher quality standard for better performance and trajectory."
ITEM.price = 900
ITEM.flag = "A"
ITEM.width = 1
ITEM.img = Material("vgui/hud/45acp.png")
ITEM.weight = 0.035
ITEM.isAmmo = true