ITEM.name = "4.6x30mm Match grade"
ITEM.model = "models/kek1ch/ammo_762x25_p.mdl"
ITEM.ammo = "4.6x30MM -MG-" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 4.6x30mm ammo."
ITEM.longdesc = "The HK 4.6×30mm cartridge is a type of ammunition primarily used in the Heckler & Koch MP7 personal defense weapon . It is designed to minimize weight and recoil while increasing penetration of body armor. It features a bottlenecked case and a pointed, steel-core, brass-jacketed bullet. These rounds are Match Grade."
ITEM.price = 1950
ITEM.flag = "A"
ITEM.weight = 0.008
ITEM.isAmmo = true