ITEM.name = "6.8 SPC"
ITEM.model = "models/kek1ch/ammo_556x45_ap.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "6.8SPC" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 6.8 ammo. "
ITEM.longdesc = "The 6.8mm SPC cartridge was designed to adress the deficiencies of the 5.56x45mm cartridge currently in service of all NATO-aligned countries. The cartridge was the result of the Enhanced Rifle Cartridge Program. The 6.8 SPC was initially developed to offer superior downrange lethality over 5.56x45mm NATO in an M16-pattern service rifle."
ITEM.price = 1800
ITEM.img = Material("vgui/hud/556x45.png")
ITEM.flag = "4"
ITEM.weight = 0.016
ITEM.isAmmo = true
