ITEM.name = "7.62x54mm Belt"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "7.62x54MMB"
ITEM.description = "A belt that contains %s rounds of 7.62x54mmR."
ITEM.category = "Ammunition"
ITEM.price = 10000
ITEM.flag = "4"
ITEM.ammoAmount = 100
ITEM.weight = 0.039
ITEM.isAmmo = true