ITEM.name = "RPG-7"
ITEM.longdesc = "The RPG-7 is a portable, reusable, unguided, shoulder-launched, anti-tank rocket-propelled grenade launcher.\nIt—along with its predecessor, the RPG-2—were designed by the Soviet Union; it is now manufactured by the Russian company Bazalt.\nThe weapon has the GRAU index 6G3. "
ITEM.description = "Multi-use rocket propelled grenade launcher."
ITEM.model = "models/weapons/w_rpg7.mdl"
ITEM.class = "cw_kk_ins2_rpg"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.height = 2
ITEM.price = 500000
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true 
ITEM.modifier = 7
ITEM.weight = 7
ITEM.flag = "A"
ITEM.Range = 100
ITEM.Pen = 12
ITEM.Mag = 35
ITEM.barrel = "medium"