ITEM.name = "12.7x55mm STs-130 Match Grade"
ITEM.model = "models/kek1ch/ammo_86x70_fmj.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "12.7x55mm -MG-" // type of the ammo
ITEM.ammoAmount = 10 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 12.7x55mm STs-130 ammo."
ITEM.longdesc = "The 12.7×55mm cartridge is used in some Russian firearms such as VKS bullpup sniper rifle and ShAK-12 bullpup battle rifle and RSh-12 revolver. The cartridge can carry a projectile weighing between from 108 grains and 1173 grains and is predominantly used to fire heavy subsonic loads. Despite being chambered in the same cartridge, the ShAK-12 (and RSh-12) would not be able to feed or chamber rounds designed for the VKS due to significant length differences in the bullet component of the cartridge and thus requires its own, shorter, loads. The ShAK-12 rounds have less range compared to the VKS with the maximum effective range of the loads reaching in between 100 and 300 metres. This box has a stamp of Match quality."
ITEM.price = 13500
ITEM.img = Material("vgui/hud/556x45.png")
ITEM.flag = "A"
ITEM.weight = 0.02
ITEM.isAmmo = true