ITEM.name = ".38 Special Match Grade"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammoAmount = 20
ITEM.ammo = ".38 Special -MG-" // type of the ammo
ITEM.description = "A box that contains .38 Special. This box has been made to a higher standard of quality for a better performance and flatter trajectory."
ITEM.category = "Ammunition"
ITEM.price = 450
ITEM.flag = "A"
ITEM.weight = 0.023
ITEM.isAmmo = true