ITEM.name = ".38 Special"
ITEM.model = "models/Items/BoxSRounds.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammoAmount = 20
ITEM.ammo = ".38 Special" 
ITEM.description = "A Box that contains .38 Special"
ITEM.category = "Ammunition"
ITEM.price = 300
ITEM.flag = "1"
ITEM.weight = 0.023
ITEM.isAmmo = true