ITEM.name = ".30 Carbine"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.ammo = ".30 Carbine" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of .30 Carbine ammo."
ITEM.longdesc = "The .30 Carbine is a rimless carbine/rifle cartridge used in the M1 carbine introduced in the 1940s. It is a light rifle round designed to be fired from the M1 carbine's 18-inch barrel. "
ITEM.flag = "1"
ITEM.price = 600
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 0.23
ITEM.isAmmo = true