ITEM.name = ".338 Lapua Magnum"
ITEM.model = "models/kek1ch/ammo_86x70_fmj.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = ".338 Lapua" // type of the ammo
ITEM.ammoAmount = 10 // amount of the ammo
ITEM.description= "A box that contains %s rounds of .338 Lapua Magnum ammo. "
ITEM.longdesc = "The .338 Lapua Magnum is a rimless, bottlenecked, centerifre rifle cartridge developed for long range military snipers. It saw usage in the War in Afghanistan and the Iraq War, and a sa result of this, became more widely available. In addition to it's military role, it is increasingly being used by hunters and civilian long-range shooting enthusiasts, and is capable of taking down big game."
ITEM.price = 10000
ITEM.img = Material("vgui/hud/556x45.png")
ITEM.flag = "4"
ITEM.weight = 0.02
ITEM.isAmmo = true