ITEM.name = ".338 Lapua Magnum"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = ".338 Lapua" 
ITEM.ammoAmount = 10 
ITEM.description= "A box that contains %s rounds of .338 Lapua Magnum ammo. "
ITEM.longdesc = "The .338 Lapua Magnum is a rimless, bottlenecked, centerifre rifle cartridge developed for long range military snipers. It saw usage in the War in Afghanistan and the Iraq War, and as a result of this, became more widely available. In addition to it's military role, it is increasingly being used by hunters and civilian long-range shooting enthusiasts, and is capable of taking down big game."
ITEM.price = 10000
ITEM.flag = "4"
ITEM.weight = 0.02
ITEM.isAmmo = true