ITEM.name = "4.6x30mm"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.ammo = "4.6x30MM" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 4.6x30mm ammo."
ITEM.longdesc = "The HK 4.6×30mm cartridge is a type of ammunition primarily used in the Heckler & Koch MP7 personal defense weapon . It is designed to minimize weight and recoil while increasing penetration of body armor. It features a bottlenecked case and a pointed, steel-core, brass-jacketed bullet."
ITEM.price = 1300
ITEM.flag = "3"
ITEM.weight = 0.008
ITEM.isAmmo = true