ITEM.name = "5.56x45mm"
ITEM.model = "models/items/ammo_556x45mm.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "5.56x45MM" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 5.56x45mm ammo. "
ITEM.longdesc = "A standard-issue NATO 5.56x45 caliber round specially designed for accurate automatic fire. Provides good ballistic characteristics, having been designed on the basis of a hunting round. Widely known under its SS109 index."
ITEM.price = 1200
ITEM.img = Material("vgui/hud/556x45.png")
ITEM.flag = "3"
ITEM.weight = 0.016
ITEM.isAmmo = true