ITEM.name = "5.45x39mm"
ITEM.model = "models/items/ammo_556x45mm.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "5.45x39MM" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 5.45x39mm ammo. "
ITEM.longdesc = "Military 5.45x39 7H10 caliber is an improved piercing round for automatic rifles of Warsaw Pact countries. Provides better accuracy than the 7.62 caliber round thanks to reduced recoil and a 100 meter increase in range."
ITEM.price = 1000
ITEM.flag = "3"
ITEM.img = Material("vgui/hud/545x39.png")
ITEM.weight = 0.015
ITEM.isAmmo = true