ITEM.name = "7.62x25mm Match Grade"
ITEM.model = "models/kek1ch/ammo_762x25_p.mdl"
ITEM.ammo = "7.62x25MM -MG-" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 7.62x25mm ammo."
ITEM.longdesc = "This 7.62x25mm round contains full metal jacket rounds with a steel penetrator and a lead core under a metal jacket. It is certified Match quality."
ITEM.price = 600
ITEM.flag = "1"
ITEM.img = Material("vgui/hud/9x18.png")
ITEM.weight = 0.016
ITEM.isAmmo = true