ITEM.name = "7.62x54mm"
ITEM.model = "models/Items/BoxMRounds.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "7.62x54MMR" // type of the ammo
ITEM.ammoAmount = 10 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 7.62x54mm ammo. "
ITEM.longdesc = "Cheap 7.62 PP (also known as 7.62 R) is a dated rifle caliber introduced in the Soviet Empire at the turn of the 19th century and was still used by the USSR after World War II. It was originally designed for the Mosin-Nagant standard-issue infantry rifle and is rather rare in the Outlands due to its dated nature. The round is very hard-hitting and has surprisingly good penetrative capabilities, even in comparison to more modern ammo types. It can also be used as a cheaper solution in the PKM machine gun."
ITEM.price = 3000
ITEM.flag = "3"
ITEM.width = 2
ITEM.height = 1
ITEM.img = Material("vgui/hud/762x54.png")
ITEM.weight = 0.039
ITEM.isAmmo = true