ITEM.name = "9x18mm Match Grade"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.ammo = "9x18MM -MG-" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 9x18mm ammo."
ITEM.longdesc = "This 9x18mm round contains full metal jacket rounds with a steel penetrator and a lead core under a metal jacket. This one was made to a higher standard for improved quality and a flatter trajectory. "
ITEM.price = 300
ITEM.flag = "A"
ITEM.img = Material("vgui/hud/9x18.png")
ITEM.weight = 0.016
ITEM.isAmmo = true