ITEM.name = "9x21mm Match Grade"
ITEM.model = "models/kek1ch/ammo_9x18_fmj.mdl"
ITEM.ammo = "9x21MM -MG-" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 9x21mm ammo. "
ITEM.longdesc = "The 9×21mm Gyurza round is a Russian handgun round designed to defeat body armor that was developed by TsNIITochMash for its SR-1 Vektor semi-automatic pistol and SR-2 Veresk submachine gun. This box has been made to a higher standard of quality for better performance and a flatter trajectory."
ITEM.price = 1950
ITEM.flag = "A"
ITEM.weight = 0.021
ITEM.isAmmo = true