ITEM.name = "9x21mm"
ITEM.model = "models/Items/BoxSRounds.mdl"
ITEM.ammo = "9x21MM" 
ITEM.ammoAmount = 30 
ITEM.description= "A box that contains %s rounds of 9x21mm ammo. "
ITEM.longdesc = "The 9×21mm Gyurza round is a Russian handgun round designed to defeat body armor that was developed by TsNIITochMash for its SR-1 Vektor semi-automatic pistol and SR-2 Veresk submachine gun."
ITEM.price = 1300
ITEM.flag = "3"
ITEM.weight = 0.021
ITEM.isAmmo = true