ITEM.name = "9x19mm Match Grade"
ITEM.model = "models/kek1ch/ammo_9x19_fmj.mdl"
ITEM.ammo = "9x19MM -MG-" // type of the ammo
ITEM.ammoAmount = 30 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 9x19mm ammo. "
ITEM.longdesc = "This basic 9x19 caliber round with a jacketed bullet has good characteristics while being simple to produce. The round is popular due to the fact that international conventions prohibit the use of expanding ammunition in combat. This one was made to a higher standard for improved quality and a flatter trajectory."
ITEM.price = 750
ITEM.flag = "A"
ITEM.img = Material("vgui/hud/9x19.png")
ITEM.weight = 0.021
ITEM.isAmmo = true