ITEM.name = "Pulse Rifle Ammo"
ITEM.model = "models/Items/combine_rifle_cartridge01.mdl"
ITEM.ammo = "ar2" 
ITEM.ammoAmount = 30 
ITEM.description= "A box that contains %s rounds of 9x18mm ammo."
ITEM.longdesc = "This 9x18mm round contains full metal jacket rounds with a steel penetrator and a lead core under a metal jacket."
ITEM.price = 200
ITEM.flag = "1"
ITEM.weight = 0.016
ITEM.isAmmo = true