ITEM.name = "Combine Alloy Scrap"
ITEM.model = "models/gibs/manhack_gib01.mdl"
ITEM.description = "A chunk of Combine alloy."
ITEM.longdesc = "A chunk of Combine alloy. It has no publicly known name or clear composition, but it almost certainly wasn't originating from Earth. It's used by the Combine to build damned near everything, but is seldom used by other groups due to how hard it is to shape with conventional metalworking tools."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 125
ITEM.width = 1
ITEM.height = 1