ITEM.name = "Silver Chain"
ITEM.model = "models/illusion/eftcontainers/chain.mdl"
ITEM.description = "A piece of bling."
ITEM.longdesc = "A chain made of Silver, typically worn by those afforded such luxuries, usually Loyalists, or those outside the Combine's standards of uniformity."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 150
ITEM.width = 1
ITEM.height = 1