ITEM.name = "Fabric Roll"
ITEM.model = "models/warz/items/sandbag_unbuilt.mdl"
ITEM.description = "A roll of textile fabrics."
ITEM.longdesc = "A roll of textile fabric material. Used in the production of upper-scale clothing. Could be valuable."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 3500
ITEM.width = 1
ITEM.height = 1