ITEM.name = "Fabric Roll"
ITEM.model = "models/mosi/fallout4/props/junk/components/cloth.mdl"
ITEM.description = "A roll of textile fabrics."
ITEM.longdesc = "A roll of textile fabric material. Used in the production of upper-scale clothing. Could be valuable."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 135
ITEM.width = 1
ITEM.height = 1