ITEM.name = "Handheld Game Console"
ITEM.model = "models/illusion/eftcontainers/tetriz.mdl"
ITEM.description = "A portable game console."
ITEM.longdesc = "Before this war, these things were all the rage. Now, they're considered contraband to own in cities unless you're above the law as some Loyalists are. In the Outlands however, these portable distractions are worth their weight in gold."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 250
ITEM.width = 1
ITEM.height = 1