ITEM.name = "Novelty Ring"
ITEM.model = "models/illusion/eftcontainers/skullring.mdl"
ITEM.description = "A novelty ring cast from a valuable material."
ITEM.longdesc = "A ring cast from a valuable enough material and a depiction of something attached or on the band itself, such as a skull, slithering snakes, or other things you'd buy from a convention stall. Worn by bandits and people who think they're cool."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 75
ITEM.width = 1
ITEM.height = 1