ITEM.name = "Novelty Coin"
ITEM.model = "models/illusion/eftcontainers/bitcoin.mdl"
ITEM.description = "A novelty coin."
ITEM.longdesc = "A coin cast from some material of decent value, with one depiction serving as Heads, and another as Tails. Used by loners for coin tricks, or by bandits and other two-faced individuals that leave things up to chance. Also sees some value from scrappers who want to melt it down for the metal."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 1