ITEM.name = "Suitable Tissue"
ITEM.model = "models/mosi/fnv/props/food/flymeat.mdl"
ITEM.description = "A slimy cut of harvested, inedible meat."
ITEM.longdesc = "A sample of Xenian tissue able to be refined into an Anti-Xenian substance. What sets this tissue apart from standard Xenian skin? Nobody knows."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 15000
ITEM.width = 1
ITEM.height = 1