ITEM.name = "Processed Alloy"
ITEM.model = "models/mosi/fallout4/props/junk/components/copper.mdl"
ITEM.description = "A strange alloy altered by Pearl's internal engineering functions."
ITEM.longdesc = "This alloy is used exclusively by Pearl to produce various tools of her use. Its exact origin is unknown, and it's strange it can be produced from steel, copper, tin, and other general metals yet share no similar properties once refined."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 15000
ITEM.width = 1
ITEM.height = 1