ITEM.name = "Powerbank"
ITEM.model = "models/illusion/eftcontainers/powerbank.mdl"
ITEM.description = "A battery-looking piece of tech."
ITEM.longdesc = "A high-capacity, USB-operated battery pack device. Used to charge rechargeable electronics on the go. Could be valuable."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 265
ITEM.width = 1
ITEM.height = 2