ITEM.name = "Reloading Powder"
ITEM.model = "models/illusion/eftcontainers/gpred.mdl"
ITEM.description = "A plastic container of grained black-powder."
ITEM.longdesc = "A one-pound container of reloading powder. Valued by survivalists and others to keep a supply of ammunition fresh. Could even be used to make very basic explosives."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 475
ITEM.width = 1
ITEM.height = 2