ITEM.name = "Reclaimed Metal"
ITEM.model = "models/gibs/metal_gib2.mdl"
ITEM.description = "A sturdy metal bar."
ITEM.longdesc = "A bar of metal, either a chunk from a professionaly made piece of metalwork, or scraps with impurities and other flaws removed. Acceptable for most uses."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 15
ITEM.width = 1
ITEM.height = 1