ITEM.name = "Sterile Syringe"
ITEM.model = "models/illusion/eftcontainers/medsyringe.mdl"
ITEM.description = "A packaged medical syringe."
ITEM.longdesc = "A medical syringe sealed inside a package, guaranteed to be sterile and safe to use. Great for assembling medical kits, or other less noble uses."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 2700
ITEM.width = 1
ITEM.height = 1