ITEM.name = "Scrap Metal"
ITEM.model = "models/props_debris/metal_panelshard01c.mdl"
ITEM.description = "A piece of low quality scrap metal."
ITEM.longdesc = "A chunk of sheet metal or other low grade metal, useful for some homemmade metalworking and little else."
ITEM.category = "junk"
ITEM.flag = "1"
ITEM.price = 5
ITEM.width = 1
ITEM.height = 1