ITEM.name = "ASD Spare Parts (SEVA)"
ITEM.model = "models/kek1ch/armor_repair_pro.mdl"
ITEM.description = "Parts that seem to belong to Anomaly Suppression Device and a Screen Helmet. Three of these and a PS-5 could result in something useful."
ITEM.category = "Parts"
ITEM.flag = "A"
ITEM.price = 19000
ITEM.width = 1
ITEM.height = 1
ITEM.weight = 1