ITEM.name = "MP-133"
ITEM.description = "The MP-133 is a Russian pump-action shotgun developed in the late 1990s from the IZh-81."
ITEM.model = "models/silver/stalker/weapons/w_mp133.mdl"
ITEM.class = "cw_sil_mp133"
ITEM.weaponCategory = "secondary"
ITEM.width = 4
ITEM.height = 1
ITEM.price = 16500 
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 1.5
ITEM.flag = "3"
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 5
ITEM.barrel = "medium"