ITEM.name = "OTs-33 Pernach"
ITEM.description= "An automatic Russian handgun that fires 9x18mm."
ITEM.longdesc = "The OTs-33 Pernach is a Russian 9x18 Makarov machine pistol, derived from the 5.45 mm OTs-23 Drotik machine pistol. The Pernach is an automatic pistol designed to replace the Stechkin APS in various special OMON units within the Russian police, the Russian Ministry of Internal Affairs (MVD) and other paramilitary units. The OTs-33 was developed in 1995 by Igor Stechkin at the TsKIB SOO design bureau, and it went into limited production at the KBP Instrument Design Bureau. It is also known as the SBZ-2, derived from the names of the KBP team responsible for the pistol, namely Stechkin, Baltser and Zinchenko.\n\nAmmo: 9x18mm\nMagazine Capacity: 18"
ITEM.model = "models/weapons/ethereal/w_pernach.mdl"
ITEM.class = "cw_kk_ins2_pernach"
ITEM.weaponCategory = "sidearm"
ITEM.width = 2
ITEM.price = 25000
ITEM.height = 1
ITEM.flag = "4"
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 18
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 1.150
ITEM.barrel = "short"