ITEM.name = "RGM-40 Kastet"
ITEM.description= "A Russian single-shot standalone grenade launcher."
ITEM.longdesc = "The RGM-40 Kastet grenade launcher is a standalone version of the Russian GP-30 grenade launcher with a telescoping stock, AK pistol grip, and flip up target sights. It is a sungle-shot weapon with a self cocking trigger mechanism, and offers a high degree of commonality with the GP-30. It uses standard 40mm VOG-25 fragmentation grenades."
ITEM.model = "models/silver/stalker/weapons/w_rgm40_item.mdl"
ITEM.class = "cw_sil_rgm40"
ITEM.weaponCategory = "sidearm"
ITEM.width = 2
ITEM.price = 70000
ITEM.height = 1 
ITEM.flag = "4"
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 1
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 2.5
ITEM.barrel = "short"
