ITEM.name = "FN SCAR-L"
ITEM.description = "A assault rifle that fires 5.56x45mm rounds."
ITEM.longdesc = "The FN SCAR (Special Operations Forces Combat Assault Rifle) is a family of gas-operated automatic rifles developed by Belgian manufacturer FN Herstal in 2004. The 'L' stands for light.\n\nAmmo: 5.56x45mm\nMagazine Capacity: 30"
ITEM.model = "models/silver/stalker/weapons/w_scarl.mdl"
ITEM.class = "cw_sil_scarl"
ITEM.weaponCategory = "primary"
ITEM.width = 4
ITEM.price = 85000
ITEM.height = 2
ITEM.Range = 400
ITEM.Pen = 18
ITEM.Mag = 30
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 3.29
ITEM.flag = "A"
ITEM.barrel = "long"