ITEM.name = "Medical Supplies"
ITEM.model = "models/kek1ch/helmet_repair.mdl"
ITEM.description = "A bag of general Medical supplies."
ITEM.longdesc = "A bag full of disposable medical equipment and medicines to resupply an ambulance, first aid point or a small doctor's office."
ITEM.category = "Medical"
ITEM.flag = "1"
ITEM.price = 5000
ITEM.width = 1
ITEM.height = 1