ITEM.name = "20g Buckshot"
ITEM.model = "models/kek1ch/ammo_12x70_buck.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "20 Gauge" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.price = 300
ITEM.description= "A box that contains %s 20 gauge shells. "
ITEM.longdesc = "Standard 20 gauge shell filled with 6 mm shot. Highly lethal at close range. Only suitable for use with smoothbore weapons."
ITEM.flag = "1"
ITEM.weight = 0.045
ITEM.isAmmo = true