ITEM.name = "5.56x45mm Belt Match Grade"
ITEM.model = "models/kek1ch/ammo_pkm.mdl"
ITEM.width = 2
ITEM.height = 1
ITEM.ammo = "5.56x45MMB -MG-"
ITEM.description = "A belt that contains %s rounds of 5.56x45mm."
ITEM.longdesc = "This belt's rounds are certified Match quality."
ITEM.category = "Ammunition"
ITEM.price = 12000
ITEM.flag = "A"
ITEM.ammoAmount = 200
ITEM.weight = 0.039
ITEM.isAmmo = true