ITEM.name = ".50AE Match Grade"
ITEM.model = "models/kek1ch/ammo_50_ae.mdl"
ITEM.ammo = ".50 AE -MG-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of .50 AE ammo. "
ITEM.longdesc = "The .50 Action Express is a large caliber handgun cartridge. Developed in 1988 by American Evan Whildin of Action Arms, the .50 AE is one of the most powerful pistol cartridges in production. These are of Match quality."
ITEM.price = 1950
ITEM.flag = "A"
ITEM.img = Material("vgui/hud/50ae.png")
ITEM.weight = 0.09
ITEM.isAmmo = true