ITEM.name = "7.62x39mm Match Grade"
ITEM.model = "models/kek1ch/ammo_762x39_fmj.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "7.62x39MM -MG-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 7.62x39mm ammo. "
ITEM.longdesc = "7.62x39 Full Metal Jacket is one the most commonly used types of ammunition, especially in Africa and in the Middle East. Some nicknamed it the 'Round of the Revolution' due to its favored use by both terrorist and criminal organizations. Due to the sheer power of the round most military organizations have turned to using additional steel plates to counter 7.62x39 as there is a high probability of encountering it in combat situations. This box is Match grade."
ITEM.price = 2025
ITEM.img = Material("vgui/hud/762x39.png")
ITEM.flag = "A"
ITEM.weight = 0.025
ITEM.isAmmo = true