ITEM.name = "9x39mm Match Grade"
ITEM.model = "models/kek1ch/ammo_9x39_pab9.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.ammo = "9x39MM -MG-" // type of the ammo
ITEM.ammoAmount = 20 // amount of the ammo
ITEM.description= "A box that contains %s rounds of 9x39mm ammo. "
ITEM.longdesc = "The SP-5 is a subsonic 9x39mm rifle round with a bimetallic casing. The round contains a steel core with a gap behind it that is filled with lead. Requires a suppressor for stealth firing. Used by special services of Warsaw Pact countries. This box was made to a higher standard for improved performance and a flatter trajectory."
ITEM.price = 2400
ITEM.img = Material("vgui/hud/9x39.png")
ITEM.weight = 0.044
ITEM.isAmmo = true
ITEM.flag = "A"