ITEM.name = "AA-12"
ITEM.description= "An automatic combat shotgun. Fires 12 gauge."
ITEM.longdesc = "The AA-12, originally designed and known as the Atchisson Assault Shotgun, is an automatic combat shotgun developed in 1972 by Maxwell Atchisson. The most prominent feature is reduced recoil. The current 2005 version has been developed over 18 years since the patent was sold to Military Police Systems, Inc. The original design was the basis of several later weapons, including the USAS-12 combat shotgun. The shotgun fires in fully automatic mode only and cannot get any attachments mounted on it unfortunately, save for flashlights and laser pointers.\n\nAmmo: 12 Gauge \nMagazine Capacity: 20"
ITEM.model = "models/weapons/aa12/w_aa12.mdl"
ITEM.class = "cw_kk_ins2_aa12"
ITEM.weaponCategory = "secondary"
ITEM.width = 4
ITEM.price = 50000
ITEM.height = 2
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 8
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 5.2
ITEM.flag = "4"
ITEM.barrel = "medium"