ITEM.name = "FAMAS F1"
ITEM.description = "A bullpup assault rifle that fires 5.56x45mm rounds."
ITEM.longdesc = "The FAMAS is a bullpup assault rifle designed and manufactured in France by MAS in 1978, a year after the Austrian Steyr AUG. It is known by French troops as 'Le Clairon' (The Bugle) due to its distinctive shape. The FAMAS is recognised for its high rate of fire at 1,100 rounds per minute.\n\nAmmo: 5.56x45mm \nMagazine Capacity: 30"
ITEM.model = "models/weapons/ethereal/w_famasf1.mdl"
ITEM.class = "cw_kk_ins2_famasf1"
ITEM.weaponCategory = "primary"
ITEM.width = 3
ITEM.price = 40000
ITEM.height = 2
ITEM.flag = "4"
ITEM.Range = 50
ITEM.Pen = 12
ITEM.Mag = 30
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 3.6
ITEM.barrel = "medium"