ITEM.name = "G3A3"
ITEM.description = "A battle rifle that fires 7.62x51mm rounds."
ITEM.longdesc = "The G3A3 is a 7.62×51mm NATO, select-fire battle rifle developed in the 1950s by the German armament manufacturer Heckler & Koch (H&K) in collaboration with the Spanish state-owned design and development agency CETME.\n\nAmmo: 7.62x51mm\nMagazine Capacity: 20"
ITEM.model = "models/weapons/ethereal/w_g3a3.mdl"
ITEM.class = "cw_kk_ins2_g3a3"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.price = 220000
ITEM.height = 2
ITEM.Range = 150
ITEM.Pen = 18
ITEM.Mag = 20
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 4.38
ITEM.flag = "A"
ITEM.barrel = "long"