ITEM.name = "MP-443 Grach"
ITEM.description = "The MP-443 Grach, following traditional Russian naming procedure, is the Russian standard military-issue side arm. It fires 9x19 rounds."
ITEM.model = "models/weapons/ethereal/w_grach.mdl"
ITEM.class = "cw_sil_grach"
ITEM.weaponCategory = "sidearm"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 4000
ITEM.flag = "3"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 11
ITEM.weight = 0.95
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 18
ITEM.barrel = "short"