ITEM.name = "KS-23"
ITEM.description = "The KS-23 is a Russian shotgun, although because it uses a rifled barrel it is officially designated by the Russian military as a carbine. KS stands for Karabin Spetsialniy, 'Special Carbine'. It is renowned for its large caliber, firing a 23 mm round, equating to 6.27 gauge using the British and American standards of shotgun gauges and approximately 4 gauge using the current European standards (based on the metric CIP tables), making it the largest-bore shotgun in use today."
ITEM.model = "models/weapons/ethereal/w_ks23.mdl"
ITEM.class = "cw_sil_ks23"
ITEM.weaponCategory = "secondary"
ITEM.width = 4
ITEM.height = 2
ITEM.price = 120000
ITEM.flag = "A"
ITEM.isWeapon = true
ITEM.isPLWeapon = true 
ITEM.isCW = true
ITEM.modifier = 27
ITEM.weight = 5
ITEM.Range = 25
ITEM.Pen = 18
ITEM.Mag = 3
ITEM.barrel = "short"