ITEM.name = "Mossberg 88"
ITEM.description = "The Maverick 88 is a pump action shotgun manufactured by O.F. Mossberg & Sons. The Maverick 88 is virtually identical to the Mossberg 500. Factory Maverick 88s feature a black, synthetic only stock and forearm, cylinder bore (although interchangeable chokes are available on some hunting models), and cross-bolt safety. Most accessories are interchangeable with a Mossberg 500."
ITEM.model = "models/weapons/ethereal/w_chaser13.mdl"
ITEM.class = "cw_sil_mossberg88"
ITEM.weaponCategory = "secondary"
ITEM.width = 3
ITEM.height = 1 
ITEM.price = 16000
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 20
ITEM.weight = 2.720
ITEM.flag = "3"
ITEM.Range = 50
ITEM.Pen = 5
ITEM.Mag = 6
ITEM.barrel = "medium"