ITEM.name = "Colt Python"
ITEM.description = "The Colt Python is a .357 Magnum caliber revolver manufactured by Colt's Manufacturing Company of Hartford, Connecticut. It was first introduced in 1955, and is intended for the premium revolver market segment. Some firearms collects have described it as the finest revolver ever made. Chambered for .357 Magnum."
ITEM.model = "models/weapons/ethereal/w_python.mdl"
ITEM.class = "cw_sil_python"
ITEM.weaponCategory = "sidearm"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 24000
ITEM.flag = "4" 
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 2
ITEM.weight = 1.1
ITEM.Range = 30
ITEM.Pen = 4
ITEM.Mag = 6
ITEM.barrel = "medium"