ITEM.name = "PP-2000"
ITEM.description = "Russian submachine gun that fires 9x19mm."
ITEM.longdesc = "The PP-2000 is a submachine gun/machine pistol made by the KBP Instrument Design Bureau. It was first publicly displayed at the Interpolytech-2004 exhibition in Moscow even though its patent was filed in 2001 and issued in 2003. The PP-2000 is a conventional blowback-operated weapon and weighs 1.5 kg empty. The PP-2000 is designed as a close-quarter combat weapon, intended for riot police and special operations forces. In 2008, it was adopted as one of the two standard SMGs of the Russian police along with the Vityaz-SN. It's a common sight in the zone due to the combination of stopping power brought by a submachine gun and the extremely compact and concealable nature of the weapon.\n\nAmmo: 9x19mm\nMagazine Capacity: 20"
ITEM.model = "models/silver/outbreak/weapons/w_pp2000.mdl"
ITEM.class = "cw_sil_pp2000"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 1
ITEM.price = 11000 
ITEM.flag = "1"
ITEM.isWeapon = true
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 4
ITEM.weight = 1.4
ITEM.repairCost = ITEM.price/100*1
ITEM.Range = 50
ITEM.Pen = 6
ITEM.Mag = 20
ITEM.barrel = "medium"