ITEM.name = "P220"
ITEM.description = "The SIG Sauer P220 is a full-sized, service-type pistol made by SIG Sauer. It is chambered for the .45 ACP."
ITEM.model = "models/silver/stalker/weapons/w_p220.mdl"
ITEM.class = "cw_sil_p220"
ITEM.weaponCategory = "sidearm"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 8800
ITEM.flag = "3"
ITEM.isWeapon = true
ITEM.isPLWeapon = true 
ITEM.isCW = true
ITEM.modifier = 13
ITEM.weight = 0.964
ITEM.Range = 30
ITEM.Pen = 5
ITEM.Mag = 10
ITEM.barrel = "short"