ITEM.name = "RPK-74"
ITEM.description = "The RPK-74 was introduced in 1974 together with the AK-74 assault rifle and chambered for the new 5.45×39mm intermediate cartridge. It was derived from the AK-74 rifle, with modifications that mirror those made to the AKM to create the RPK. It also uses a longer and heavier chrome-plated barrel, bipod, adjusted gas channel in the gas block, and a different front sight tower."
ITEM.model = "models/silver/stalker/weapons/w_rpk74.mdl"
ITEM.class = "cw_sil_rpk74"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.height = 2
ITEM.price = 45000
ITEM.flag = "3"
ITEM.isWeapon = true 
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 5
ITEM.weight = 4.4
ITEM.Range = 150
ITEM.Pen = 12
ITEM.Mag = 45
ITEM.barrel = "long"