ITEM.name = "FN SCAR-H"
ITEM.description = "A battle rifle that fires 7.62x51mm rounds."
ITEM.longdesc = "The FN SCAR (Special Operations Forces Combat Assault Rifle) is a family of gas-operated automatic rifles developed by Belgian manufacturer FN Herstal in 2004. The 'H' stands for heavy.\n\nAmmo: 7.62x51mm\nMagazine Capacity: 20"
ITEM.model = "models/cw2/rifles/w_scarh.mdl"
ITEM.class = "cw_kk_ins2_scarh762"
ITEM.weaponCategory = "primary"
ITEM.width = 5
ITEM.price = 250000
ITEM.height = 2
ITEM.Range = 400
ITEM.Pen = 18
ITEM.Mag = 20
ITEM.isCW = true
ITEM.isPLWeapon = true
ITEM.modifier = 5
ITEM.weight = 3.72
ITEM.flag = "A"
ITEM.barrel = "long"