ITEM.name = "Kriss Vector"
ITEM.description = "The KRISS Vector series are a family of weapons based upon the parent submachine gun design developed by KRISS USA, formerly Transformational Defense Industries (TDI). They use an unconventional delayed blowback system combined with in-line design to reduce perceived recoil and muzzle climb. This particular variant is chambered in .45 ACP."
ITEM.model = "models/weapons/ethereal/w_vector.mdl"
ITEM.class = "cw_sil_vector"
ITEM.weaponCategory = "secondary"
ITEM.width = 2
ITEM.height = 2
ITEM.price = 40000 
ITEM.flag = "3"
ITEM.isWeapon = true 
ITEM.isPLWeapon = true
ITEM.isCW = true
ITEM.modifier = 10
ITEM.weight = 2.7
ITEM.Range = 50
ITEM.Pen = 6
ITEM.Mag = 25
ITEM.Rld = "Ready"
ITEM.barrel = "medium"